name: morningmagic
description: A new Flutter project.

publish_to: "none"

version: 1.2.4+56

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 2.10.5
  
dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.3
  expandable: ^5.0.1
  google_mobile_ads: ^2.1.0
  firebase_analytics: ^10.0.1
  firebase_core: ^2.0.0
  firebase_storage: ^11.0.1
  cloud_firestore: ^4.0.1
  fl_chart: ^0.55.2
  flutter_audio_recorder: ^0.5.5
  flutter_circular_chart_two: ^0.1.2
  flutter_html: ^3.0.0-alpha.6
  flutter_svg: ^1.1.5
  get: ^4.6.5
  hive: ^2.0.4
  flutter_keyboard_visibility: ^5.3.0
  hive_flutter: ^1.0.0
  permission_handler: ^10.2.0
  random_string: ^2.1.0
  reorderables: ^0.5.0
  shared_preferences: ^2.0.6
  simple_animations: ^2.4.2
  url_launcher: ^6.0.3
  flutter_cache_manager: ^3.1.2
  vibration: ^1.7.3
  equatable: ^2.0.3
  in_app_review_play_store: ^0.0.3
  rate_my_app: ^1.1.0+1
  smooth_star_rating: ^1.1.1
  just_audio: ^0.9.6
  audioplayers: ^1.1.1
  multi_image_picker: ^4.8.0
  path_provider: ^2.0.2
  dots_indicator: ^2.1.0
  enum_to_string: ^2.0.1
  data_connection_checker: ^0.3.4
  flutter_local_notifications: ^12.0.2
  sliding_sheet: ^0.5.2
  percent_indicator: ^4.2.2
  facebook_app_events: ^0.17.1
  app_tracking_transparency: ^2.0.0
  flutter_gifimage: ^1.0.1
  day_night_time_picker: ^1.0.2
  duration_picker: ^1.0.1
  numberpicker: ^2.1.1
  hexcolor: ^3.0.1
  appmetrica_plugin: ^1.1.0
  adapty_flutter: ^1.0.11
  appodeal_flutter: ^1.1.2
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^3.0.1
  flutter_native_timezone: ^2.0.0
  firebase_remote_config: ^3.0.1
  provider: ^6.0.3
  get_it: 7.2.0
  install_referrer: 1.2.1
  wakelock: ^0.6.2
  auto_size_text: ^3.0.0
#  remove on fix charts flutter
dependency_overrides:
  file: ^6.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner:

  flutter_launcher_icons: ^0.10.0

flutter:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/onboarding/version_second_images/
    - assets/images/onboarding/version_third_images/
    - assets/images/paywall/
    - assets/images/auth/
    - assets/images/faq/
    - assets/images/home_menu/
    - assets/images/startscreen/morning/
    - assets/images/startscreen/afternoon/
    - assets/images/startscreen/evening/
    - assets/images/startscreen/night/
    - assets/images/interview/
    - assets/images/targets/
    - assets/images/packageImages/
    - assets/images/fitnes/
    - assets/images/fitnes/ex/
    - assets/images/fitnes/ex/program_1/
    - assets/images/fitnes/ex/program_2/
    - assets/images/fitnes/ex/program_3/
    - assets/images/fitnes/ex/program_4/
    - assets/images/visualisation/
    - assets/images/reading/
    - assets/images/diary/
    - assets/images/instrumental/
    - assets/images/diary/note/
    - assets/images/meditation/
    - assets/images/affirmation/
    - assets/images/purchase/
    - assets/images/svg/
    - assets/images/timer/
    - assets/images/reading_night/
    - assets/audios/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/BrandIcons/BrandIcons.ttf

  uses-material-design: true
