name: morningmagic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^1.3.1+2
  audioplayers: ^0.16.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  expandable: ^4.1.4
  firebase_analytics: ^5.0.2
  firebase_core: ^0.5.2+1
  fl_chart: ^0.12.0
  flutter_audio_recorder: ^0.5.5
  flutter_circular_chart: ^0.1.0
  flutter_html: ^0.8.2
  flutter_svg: ^0.19.0
  get: ^3.17.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  permission_handler: ^5.0.1+1
  purchases_flutter: ^1.2.1
  random_string: ^2.1.0
  reorderables: ^0.3.2
  shared_preferences: ^0.5.12
  simple_animations: ^2.2.2
  url_launcher: ^5.7.10
  vibration: ^1.5.0
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:

  flutter_launcher_icons: "^0.8.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  assets:
    - assets/svg/
    - assets/images/
    - assets/audios/
    - assets/langs/

  fonts:
    - family: Junegull-Regular
      fonts:
        - asset: assets/fonts/1440.ttf

    - family: rex
      fonts:
        - asset: assets/fonts/Rex-Bold.ttf

    - family: aparaj
      fonts:
        - asset: assets/fonts/aparaj.ttf

    - family: JMH
      fonts:
        - asset: assets/fonts/JMH.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
