name: morningmagic
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.2
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.0
  expandable: ^4.1.4
  firebase_analytics: ^7.0.1
  firebase_core: ^0.7.0
  firebase_admob: ^0.11.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  fl_chart: ^0.12.0
  flutter_audio_recorder: ^0.5.5
  flutter_circular_chart_two: ^0.1.2
  flutter_html: ^0.8.2
  flutter_svg: ^0.19.3
  flutter_visualizers: ^0.0.2
  get: ^3.26.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  permission_handler: ^5.0.1+1
  purchases_flutter: ^1.4.3
  random_string: ^2.1.0
  reorderables: ^0.3.2
  shared_preferences: ^0.5.12+4
  simple_animations: ^2.4.2
  url_launcher: ^5.7.10
  flutter_cache_manager: ^2.1.1
  vibration: ^1.7.3
  equatable: ^1.2.5
  in_app_review_play_store: ^0.0.3
  rate_my_app: ^0.7.2
  smooth_star_rating: ^1.1.1
  screen: ^0.0.5
  just_audio: ^0.6.9
  multi_image_picker: ^4.8.0
  path_provider: ^1.6.27
  dots_indicator: ^1.2.0
  enum_to_string: ^1.0.14
  data_connection_checker: ^0.3.4
  flutter_local_notifications: ^4.0.1+2
  sliding_sheet: ^0.4.0
  percent_indicator: ^3.0.1
  facebook_app_events: ^0.11.2
  app_tracking_transparency: ^2.0.0

  flutter_localizations:
    sdk: flutter

#  remove on fix charts flutter
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  sqflite: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
    - assets/images/interview/
    - assets/images/targets/
    - assets/images/fitnes/
    - assets/images/fitnes/ex/
    - assets/images/fitnes/ex/program_1/
    - assets/images/fitnes/ex/program_2/
    - assets/images/fitnes/ex/program_3/
    - assets/images/fitnes/ex/program_4/
    - assets/images/visualisation/
    - assets/images/reading/
    - assets/images/diary/
    - assets/images/diary/note/
    - assets/images/meditation/
    - assets/images/affirmation/
    - assets/images/purchase/
    - assets/images/svg/
    - assets/images/timer/
    - assets/audios/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

  uses-material-design: true
