Map<String, String> translations_en = {
  'onb_3_1_title': 'If not now,\n    when?',
  'onb_3_1_subtitle':
      'Start taking care of yourself and\nforming morning habits that will\n      change your life forever',
  'onb_3_2_title_1': 'What time do you usually\n',
  'onb_3_2_title_2': 'wake up?',
  'onb_3_3_title_1': 'Do you tend\n',
  'onb_3_3_title_2': 'to procrastinate?',
  'onb_3_3_item_1_name_1': 'Yes, and ',
  'onb_3_3_item_1_name_2': 'I want to\nchange that',
  'onb_3_3_item_2_name_1': 'No, ',
  'onb_3_3_item_2_name_2': 'I can easily stick\nto my plan',
  'onb_3_3_item_3_name_1': "I'm ",
  'onb_3_3_item_3_name_2': 'not sure',
  'onb_3_4_title_1': 'Do you have trouble\n',
  'onb_3_4_title_2': 'concentrating?',
  'onb_3_4_item_1_name_1': 'Yes, ',
  'onb_3_4_item_1_name_2': 'I get distracted\neasily',
  'onb_3_4_item_2_name_1': 'No, ',
  'onb_3_4_item_2_name_2': "I can focus well\nand don't get\ndistracted",
  'onb_3_4_item_3_name_1': "I'm ",
  'onb_3_4_item_3_name_2': 'not sure',
  "nexting": "Continue",
  'onb_3_5_title_1': 'What do you want ',
  'onb_3_5_title_2': 'to get\nout of My Morning?',
  'onb_3_5_item_1_name_1': 'I want to ',
  'onb_3_5_item_1_name_2': 'form good\nhabits',
  'onb_3_5_item_2_name_1': 'I want to ',
  'onb_3_5_item_2_name_2': "plan my\nday better",
  'onb_3_5_item_3_name_1': "I'm ",
  'onb_3_5_item_3_name_2': 'not sure',
  "lets go": "Let's go!",
  "subscription": "Subscription",
  "settings_desc": "Set up your complex",
  "start_complex": " Morning complex",
  "set_timer": "Set timer",
  "dont_add_time": "Don't change time",
  "select": "Select",
  "Continue": "Continue",
  "How much": "How much ",
  "sleep": "sleep ",
  "do you usually get at hight": "do you\n usually get at night?",
  "Morning": "Morning",
  "hours": " hours",
  "hours or": " hours or ",
  "less": "less",
  "more": "more",
  "Evening": "Evening",
  "Unlock all features": "Unlock all features\n",
  "Build your perfect morning routine": "Build your perfect morning routine",
  "Got it! Do you": "Got it! Do you ",
  "wake up": "wake up\n ",
  "feeling well-rested?": "feeling well-rested?",
  "Always": "Always",
  "Usually": "Usually",
  "Sometimes": "Sometimes",
  "High ": "High ",
  "Medium ": "Medium ",
  "meditation is complete": "Meditation is complete",
  "Low ": "Low ",
  "- energized troughot the day": "- energized throughout the day",
  "- i have bursts of energy": "- I have bursts of energy",
  "- my energy fades troughout the day": "- my energy fades throughout the day",
  "How satisfied are you with your ": "How satisfied are you\n with your ",
  "current fitness level?": "current fitness\nlevel?",
  "Completeli ": "Completely ",
  "Somewhat ": "Somewhat ",
  "Not at all ": "Not at all ",
  "- I feel fit and healthy": "- I feel fit and healthy",
  "- I'd like to see some                 improvement":
      "- I'd like to see some\n                 improvement",
  "- I'd like to see a major change": "- I'd like to see a major change",
  "Over the past year, what's been ": "Over the past year, what's\nbeen ",
  'your experience': 'your experience\n',
  " building better habits?": " building better habits?",
  "I have been ": "I have been ",
  "I have built ": "I have built ",
  "I have tried t build good habits,": "I have tried to build good habits,\n",
  "I have not tried ": "I have not tried ",
  "constantly improving my habits": "constantly\nimproving my habits",
  "some good habits": "some good\nhabits",
  "but have not kept up with them": "but have not kept up with them",
  "to build new habits": "to build new\nhabits",
  "Rarely": "Rarely",
  "7one": "",
  "7two": "",
  "7tree": "",
  "7four": "",
  "More  ": "More  ",
  "energy": "energy",
  "productivity": "productivity",
  "mindfulness": "mindfulness",
  "Sleep": "sleep",
  "We hear you. What single change ": "We hear you. What single\n change ",
  "would improve your life right now?": "would improve\n your life right now?",
  "8tree": "",
  "How often ": "How often ",
  "do you focus": "do you focus\n",
  "on the past or futue?": "on the past or future?",
  "Never ": "Never ",
  "Some ": "Some ",
  "Most ": "Most ",
  "All ": "All ",
  "of the time1": "of the time",
  "of the time2": "of the time",
  "of the time3": "of the time",
  "How ": "How ",
  " are you?": " are you?",
  "distractable": "distractable\n",
  "Easily ": "Easily ",
  "Sometimes ": "Sometimes ",
  "Rarely ": "Rarely ",
  "Laser ": "Laser ",
  "distracted": "distracted",
  "lose focus": "lose focus",
  " focus": "focus",
  "You're embarking on this journey ": "You're embarking on\nthis journey ",
  "to build more Energy": "to build\nmore Energy",
  "Fitness": "Fitness",
  "Visualization": "Visualization",
  "Monthly": "Monthly",
  "/month,\ncancel anytime": "/month,\ncancel anytime",
  "/year,\ncancel anytime": "/year,\ncancel anytime",
  ", one-\ntime payment": ", one-\ntime payment",
  "Annually": "Annually",
  "Lifetime": "Lifetime",
  "Restore": "Restore",
  "Terms": "Terms",
  "Privacy": "Privacy",
  "month, cancel anytime": "/month,\ncancel anytime",
  "year, cancel anytime": "/year,\n cancel anytime",
  "one-time payment": "one-time\n payment",
  "Start 3 days free trial": "Start 3 days free trial",
  "Meditationse": "Meditations",
  "your entire morning routine in one app":
      "your entire morning\nroutine in one app",
  "Reading": "Reading",
  "Just ": "Just ",
  "Customize the sequence and duration of your rituals in the Settings section.":
      "Customize the sequence and duration of your rituals in the Settings section.",
  "30 minutes every day for a year ": "30 minutes every day\nfor a year ",
  "will change your life dramatically!": "will change your\nlife dramatically!",
  "Ready": "Ready\n",
  "to start?": "to start?",
  "Notes": "Notes",
  "Affirmations": "Affirmations",
  "We’re finalizing your personalized journey...":
      "We’re finalizing your\npersonalized journey...",
  "I live in the present": "- I live in the present",
  "minutes": "minutes",
  "How much time ": "How much time ",
  "Understood! Throughout your day, how are your":
      "Understood! Throughout\n your day, how are your\n",
  "energy levels": "energy levels?",
  "energy levels two": "",
  "do you have ": "do\n you have ",
  "at the start of your day?": "at the start\nof your day?",
  "Change your life with": "Change your life with \n",
  "morning rituals": "morning rituals",
  "Set your own time": "Set your own time",
  "Statistics": "Statistics",
  "Notifications": "Notifications",
  "How much time are you going to read": "How much time are you going to read?",
  "own_time": "Own time",
  "1_hour": "1 hour",
  "Choose an affirmation": "Choose an affirmation",
  "input your name": "Input Your name",
  "thanks_to_interview":
      "Thank you very much, we will definitely listen to you!",
  "help_us": "Help us",
  "Complete": "Complete",
  "Add note": "Add note",
  "Save note": "           Save note           ",
  "Recording paused": "Recording paused",
  "Mindful minutes per week": "Mindful minutes per week",
  "Recording in progress": "Recording in progress",
  "Write something here..": "Write something here..",
  "more_not_show": "Do not show again",
  "interview_dialog_text":
      "Hey! Do you want 14 days of free trial? \n\n Then take the survey and help us make this app better!",
  "interview_dialog_text_vip":
      "Hey! Thank you for using the full version of the application, We want to make it better, so we will be grateful for the survey we took.",
  "question_1":
      "Let's get acquainted. Tell me about yourself: age, gender, country (optional)",
  "question_2": "Is it hard for you to wake up in the morning?",
  "question_2_subquestion_1": "If so, why?",
  "question_3": "Do you use apps to improve your mental and physical health?",
  "question_3_subquestion_1": "If so, what?",
  "question_4": "Do you like our free features?",
  "question_5": "Why did you choose our product?",
  "question_6": "What did you need when you were looking for our product?",
  "question_7": "Did you find what you were looking for?",
  "question_8": "What benefits do you get from our app?",
  "question_9": "What functions do you need?",
  "question_10":
      "What would you add? What would you remove? What would you change?",
  "question_11": "In your opinion, is it good idea to introduce day practices?",
  "question_11_subquestion_1": "If so, what? (breathing, daytime fitness)",
  "question_12":
      "In your opinion, is it good idea to introduce night practices",
  "question_12_subquestion_1": "If so, what? (sleep sounds, sleep preparation)",
  "question_13":
      "If you would like to participate in an interview with us, please leave your e-mail for further communication",
  "interview_2_q_1":
      "Let's get acquainted. Tell me about yourself: age, gender, country (optional)",
  "interview_2_q_2": "Did the app not meet your expectations? Why",
  "interview_2_q_3": "Did you like our free features?",
  "interview_2_q_4": "What benefits did you get from our app?",
  "interview_2_q_5": "What functions do you consider necessary?",
  "interview_2_q_6":
      "What would you add? What would you remove? What would you change?",
  "interview_2_q_7":
      "In your opinion, is it good idea to introduce day practices?",
  "interview_2_q_7_sub_1": "If so, what? (breathing, daytime fitness)",
  "interview_2_q_8":
      "In your opinion, is it good idea to introduce night practices",
  "interview_2_q_8_sub_1": "If so, what? (sleep sounds, sleep preparation)",
  "interview_2_q_9":
      "If you would like to participate in an interview with us, please leave your e-mail for further communication",
  "please_fill_all_fields": "Please fill in all fields",
  "lets_acquainted": "let's get \nacquainted",
  "welcome_page_title": "Nice to \nmeet you!",
  "welcome_page_subtitle":
      "This application is designed for your comfort. Short meditation lessons, along with other complexes, will help you meet the morning with vigor, relieve stress, tune in for the day and sleep better at night.",
  "welcome_push_title": "When would you\n like to wake up?",
  "welcome_push_subtitle":
      "Choose the time, and we will make sure that you don’t oversleep",
  "start_input": "Start writing ...",
  "start": "Start",
  "progress_item": "Progress",
  "settings": "Settings",
  "pay": "Buy subscription",
  "store_app": "Store",
  "user_is_pro": "Subscribed",
  "tarif_plans": "Tariff plan",
  "tarif_plans_done": "Subscribed",
  "upsell_screen": "Advance purchase",
  "loading_buy": "Loading",
  "loading_buy_app_bar": "Loading...",
  "start_fitness_my_program": "Start your program",
  "awareness_meter": "Awareness\nmeter",
  "month": "Month",
  "year": "Year",
  "total": "Total",
  "for_week": "For week\n",
  "skip_note": "skip",
  "skip": "Skip",
  "pages_note": "pages",
  "pages_short": "pages",
  "minutes_per_week": "minutes",
  "monday_short": "mn",
  "have_not_sub": "You are not subscribed",
  "no_sound": "No Sounds",
  "tuesday_short": "ts",
  "wednesday_short": "wd",
  "thursday_short": "th",
  "tutorial_asset": "assets/audios/tutorial_eng.mp3",
  "friday_short": "fr",
  "saturday_short": "st",
  "sunday_short": "sn",
  "count_of_sessions": "Amount\nof completed\npractice",
  "minutes_of_awareness_with_myself": "Minutes\nof awareness\nwith myself",
  "count_of_completed_sessions": "Amount \nCompleted \ncomplexes",
  "my_diary": "My diary",
  "my_exercises": "My exercises",
  "my_affirmations": "My affirmations",
  "my_books": "My books",
  "my_visualization": "My visualizations",
  "choose_ready": "Choose one",
  "add_note": "Add a note",
  "PREMIUM activated": "PREMIUM activated",
  "Add your": "Add your",
  "Start": "Start reading",
  "Starting": "Start",
  "al": "Apply",
  "Try PREMIUM Package for free": "Try PREMIUM Package for free",
  "Choose favorite meditations": "Choose favorite\n meditations",
  "Finish meditating": "Finish meditating",
  "5 min": "5 minutes",
  "10 min": "10 minutes",
  "min 1": "minutes",
  "2 min": "2 minutes",
  "3 min": "3 minutes",
  "Fitnes": "Fitness",
  "Edit": "Edit",
  "15 min": "15 minutes",
  "Favorites": "Favorites",
  "Meditations": "Meditations",
  "You haven't added any meditations to your favorites":
      "You haven't added\n any meditations\nto your Favorites yet",
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Sun': 'Sun',
  'Jan': 'Jan',
  'Feb': 'Feb',
  'Mar': 'Mar',
  'Apr': 'Apr',
  'May': 'May',
  'Jun': 'Jun',
  'Jul': 'Jul',
  'Aug': 'Aug',
  'Sep': 'Sep',
  'Oct': 'Oct',
  'Nov': 'Nov',
  'Dec': 'Dec',
  "faq": "FAQ",
  "reading": "READING",
  "reading_title":
      "Get into a comfortable position and\nprepare yourself for a book",
  "next_button": "Next",
  "progress": "PROGRESS",
  "progress_title": "You have not had any wonderful morning.",
  "back_button": "Back",
  "check internet connection": "check internet connection",
  "timer": "Timer",
  "exercise": "Exercise @id",
  "listen_to": "Listen to it",
  "next_exercise": "Next exercise",
  "program_1": "Yoga. “Sun Salutation - Surya Namaskar”",
  "program_1_ex_1_name": "Hasta Uttanasana",
  "program_1_ex_1_desc":
      "•	Stand erect and raise both the hands above the head. Let there be shoulders length between the two arms.\n•	Raising the arms and bending the trunk backwards is done at the same time. Breathe in deeply while raising the arms. \n•	Stand back to the starting position.",
  "program_1_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHasta%20Uttanasana.mp3?alt=media&token=c010bab3-eb1f-4cd6-9199-d12b2836ed26',
  "program_1_ex_2_name": "Uttanasana",
  "program_1_ex_2_desc":
      "•	Stand up tall and take a deep breath\n•	On an exhalation, extend your torso down.\n•	Stay long throughout your neck without rounding your back.",
  "program_1_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FUttanasana.mp3?alt=media&token=60ed84bd-c90e-4ffa-b5ac-f12990c4b613',
  "program_1_ex_3_name": "Ashwa Sanchalanasana",
  "program_1_ex_3_desc":
      "•	Get in the downward face dog pose.\n•	Exhale and bring your right knee toward your nose. Keep your right knee bent at a 90-degree angle\n•	Raise your arms towards the sky, lower your left knee down and slide the right knee back into the Table position, or alternatively step the right foot back into Downward Facing Dog.  ",
  "program_1_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAshwa%20Sanchalanasana.mp3?alt=media&token=adac340e-29b7-4b46-a2b5-4015c65c2a04',
  "program_1_ex_4_name": "Adho Mukha Svanasana",
  "program_1_ex_4_desc":
      "•	Set up on all fours with your hands about 3 inches ahead of your shoulders and shoulder-width apart.\n•	Inhale. Exhale and get in the downward-facing dog pose. Press down firmly with your fingertips to pull your forearms toward the front of the room. You can bend your knees.\n•	Go back in the starting position.​",
  "program_1_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAdho%20Mukha%20Svanasana.mp3?alt=media&token=2499d895-ebf7-44cd-8255-1b51d52a33b1',
  "program_1_ex_5_name": "Bhujangasana",
  "program_1_ex_5_desc":
      "1. Lie down flat on your stomach.\n2. Place your palms flat on the ground directly under your shoulders\n3. Inhale to lift your chest off the floor. Keep your buttocks and legs stretched.",
  "program_1_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBhujangasana.mp3?alt=media&token=fe0835bb-cca4-4141-9651-678c0fac3f28',
  "program_1_ex_6_name": "Gomukhasana",
  "program_1_ex_6_desc":
      "Begin in a seated cross-legged position as it is in the picture\n•	Inhale and bring your arms straight up toward the ceiling. Exhale and clasp hands behind your back.\n•	Get back in the starting position and alternate your legs and arms. ",
  "program_1_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FGomukhasana.mp3?alt=media&token=47a01e08-b6b7-4045-8aa9-733bc7a39fc2',
  "program_2": "Good spirits",
  "program_2_ex_1_name": "Walk-in-Place",
  "program_2_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FWalk-in-Place.mp3?alt=media&token=0210ca41-b307-43bf-8e83-1e360d9b9422',
  "program_2_ex_1_desc":
      "•	Stand upright, arms at side \n•	Lift right leg, lower right leg; lift left leg, lower left leg",
  "program_2_ex_2_name": "Standing Side Bend",
  "program_2_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend.mp3?alt=media&token=51ad278d-44e8-49bc-9b11-99a5b8b074a4',
  "program_2_ex_2_desc":
      "	•	Stand tall with feet and legs shoulder width apart.\n•	Lower your right arm down the right side of your body and exhale as you lengthen the left arm over the head, bending body gently to the right. Exhale as you repeat on the left side.",
  "program_2_ex_3_name": "Squats with body-rotation",
  "program_2_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20body-rotation.mp3?alt=media&token=418c6afc-3ec0-48b6-a6e8-6a36dc9ed335',
  "program_2_ex_3_desc":
      "•	Stand straight with feet shoulder width apart. \n•	Do a squat. \n•	Then, drive through heels to stand up, lifting arms overhead to the right. Transfer the weight to the right feet, left feet on raised toes. \n•	Bend knees into a squat, stand up to a different side.​",
  "program_2_ex_4_name": "Balance",
  "program_2_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBalance.mp3?alt=media&token=2d14b8ed-bcda-4ee2-a56f-959e3203e8c9',
  "program_2_ex_4_desc":
      "	•	Stand upright, arms at side. Take the right leg up and bend it.​ \n•	Stand on the left leg stretch your hands upfront and lift your left leg behind you. ​\n•	Hold the position for some time and stand straight. \n•	Replace the legs. ",
  "program_2_ex_5_name": "Bridge",
  "program_2_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBridge.mp3?alt=media&token=efbe555e-42b7-4673-b290-36c5b78ccb38',
  "program_2_ex_5_desc":
      "•	Lie on your back with your hands at your sides, knees bent, and feet flat on the floor under your knees. \n•	Raise your hips to create a straight line from your knees to shoulders. Tighten your abdominal and buttock muscles \n•	Complete at least 20 reps.​",
  "program_3": "Move mountains",
  "program_3_ex_1_name": "Standing Side Bends ",
  "program_3_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend%20copy.mp3?alt=media&token=23112729-ce26-48d7-9bd6-66f7a86a404e',
  "program_3_ex_1_desc":
      "	•	Stand tall with feet and legs shoulder width apart. \n•	Put your right arm the right hip and exhale as you lengthen the left arm over the head, bending body gently to the right. Exhale as you repeat on the left side.",
  "program_3_ex_2_name": "Squats with Jumps",
  "program_3_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20Jumps.mp3?alt=media&token=8c827f9b-0cc8-4530-baf7-0e1a306f290f',
  "program_3_ex_2_desc":
      "	•	Stand with heels wider than shoulder-distance apart, toes turned out slightly \n•	Bend at knees, sit hips back, and lower down into a squat, dropping arms down to touch floor between legs. \n•	Then, drive through heels to jump up, holding hands crossed on the chest. \n•	Perform some reps.​",
  "program_3_ex_3_name": "Pushups",
  "program_3_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPushups.mp3?alt=media&token=46aafc2a-66e6-47c1-930a-320aad5148d2',
  "program_3_ex_3_desc":
      "	•	Start in a standard push-up position \n•	Bend your elbows \n•	Perform some reps.​ \n•	If it is too difficult step your knees back behind and do the exercise. ",
  "program_3_ex_4_name": "Plank Twists",
  "program_3_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPlank%20Twists.mp3?alt=media&token=1d51db42-410f-4d5b-ae86-f6ce94037e8a',
  "program_3_ex_4_desc":
      "	•	Start in a plank position. \n•	Pull your belly button in towards your spine as firm as you can. \n•	Then begin to raise your chest and one arm towards the ceiling. \n•	Return back to plank. Repeat on the other side",
  "program_3_ex_5_name": "Cats Dogs exercise",
  "program_3_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCats%20Dogs%20exercise.mp3?alt=media&token=b738846e-0c8a-41f9-9cc7-535217192b07',
  "program_3_ex_5_desc":
      "	•	Get down on all fours with your weight evenly distributed. Knees under your hips. Your head and neck in a straight line with your spine. \n•	Inhale and lift your head until you’re looking forwards. \n•	Exhale and pull your belly button to your spine, bring your hips forwards. Tuck your chin into your chest. \n•	Repeat for the desired number of repetitions.",
  "program_4": "Healthy Neck",
  "program_4_ex_1_name": "Side Tilt",
  "program_4_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Tilt.mp3?alt=media&token=fe2671d0-c001-4ccd-8a09-8ff380a75355',
  "program_4_ex_1_desc":
      "•	Hold your head straight. \n•	Put your right hand on the left ear and gently bend your head to the right shoulder, stop if you feel discomfort. \n•	Change hands. ",
  "program_4_ex_2_name": "Forward and Backward Tilt",
  "program_4_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FForward%20and%20Backward%20Tilt.mp3?alt=media&token=346ffde3-4cd3-460c-928e-9f9ab177512f',
  "program_4_ex_2_desc":
      "•	Start with your head and back straight. \n•	Lower your chin toward your chest and get back to the start position. \n•	Tilt your chin up toward the ceiling and bring the base of your skull toward your back. \n•	Repeat the set several times.",
  "program_4_ex_3_name": "Side Rotation",
  "program_4_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Rotation.mp3?alt=media&token=da9612fe-6559-47ce-83a1-a52a037ce63f',
  "program_4_ex_3_desc":
      "•	Keep your head squarely over your shoulders and your back straight. \n•	Slowly turn your head to the right and left until you feel a stretch in the side of your neck and shoulder.",
  "program_4_ex_4_name": "Head rotation",
  "program_4_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHead%20rotation.mp3?alt=media&token=c5817357-2218-400a-bde1-3d8509c1dbb3',
  "program_4_ex_4_desc":
      "•	Sit or stand with your head and back straight. \n•	Rotate your head clockwise and counter clockwise 3 times.",
  "program_4_ex_5_name": "Shoulders rotation",
  "program_4_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FShoulders%20rotation.mp3?alt=media&token=ad9f4128-bbe2-42b1-be88-4f9a3a75310e',
  "program_4_ex_5_desc":
      "•	Place your legs at shoulder-width, keep your arms relaxed. \n•	Gently perform both shoulders rotation clockwise and counter clockwise.",
  "program_4_ex_6_name": "Cow Face Pose",
  "program_4_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCow%20Face%20Pose.mp3?alt=media&token=1654d6bc-dba2-4063-a674-9bd4519eb110',
  "program_4_ex_6_desc":
      "•	Stand straight, keep your shoulders relaxed. \n•	Clasp hands behind your back, so one arm is up, another is down. Feel the stretch. \n•	Change hands and do again. ",
  "exercise_1_title": "Stretching",
  "exercise_1_text":
      "Start with stretching. \n\n1. Stand straight with your feet open wider than shoulder width.\n\n2. Standing, clasp your hands straight up overhead, palms facing the ceiling.\n\n3. Slowly stretch up feeling a stretch in your body.\n\n4. Keep your head and back straight, don’t bend.\n\n5. Hold for 10 to 15 seconds, repeating three to four times.",
  "exercise_2_title": "March in Place",
  "exercise_2_text":
      "1. Human feet have plenty of sensitive points, which are responsible for the work of organs. \n\n2. Stand with feet shoulder length apart, and keep spine straight with hips facing forward. Bring your knee up so that your thigh is parallel to floor then place it down and bring the other leg up in an alternating fashion.\n\n3. Repeat up to fifty seconds.",
  "exercise_3_title": "Heel and Toe Raises",
  "exercise_3_text":
      "1. Stand up straight.\n\n2. Place your feet in 15 inches from each other.\n\n3. Inhale and roll the heels to toes, exhale and gently unroll back to the heels\n\n4. Repeat it from 20 to 25 times.",
  "exercise_4_title": "Rotations",
  "exercise_4_text":
      "1. The best way to warm up is rotational exercises.\n\n2. Begin with your head then to wrists, elbows, shoulders, feet, ankles and knees.\n\n3. Repeat it on every part of your body at least 10 tries to each side.",
  "exercise_5_title": "Alternating bend and squats",
  "exercise_5_text":
      "Simple, but effective exercise helps to improve many important muscles. \n\n1. Stand straight with your feet open wider than shoulder width,  hold hands on the waist.\n\n2. Gently bend down keeping your back flat and do one squat.\n\n3. Pay attention to your posture to prevent injuries of knees.\n\n4. Do 10-20 tries.",
  "exercise_6_title": "Standing Side Bend",
  "exercise_6_text":
      "1. Stand with your feet a little wider than hip distance apart.\n\n2. Raise your right hand.\n\n3. Lower your right arm down the right side of your body and exhale as you lengthen the left arm over the head, bending body gently to the right.\n\n4. Inhale to return arms overhead to center and exhale as you repeat on the left side.\n\n5. Repeat it at least 15 times to each side",
  "exercise_7_title": "Bicycle Crunch",
  "exercise_7_text":
      "1. Lay with the back on the floor.\n\n2. Your feet should be on the floor and your hands are behind your head.\n\n3. With your hands gently holding your head, pull your shoulder blades back and slowly raise your knees to about a 90-degree angle, lifting your feet from the floor.\n\n4. Rotate your torso so you can touch your elbow to the opposite knee as it comes up.\n\n5. Aim for 15 repetitions for each leg.",
  "exercise_8_title": "Cat and Dog",
  "exercise_8_text":
      "This exercise improves flexion\n and extension of the spine. \n\n1. Put your hands and knees on the ground.\n\n2. In one fluid movement, arch your back, suck in your stomach, and bring your hips forward.\n\n3. Now look up rather than into your legs or at the floor.\n\n4. Repeat it at least 15 times to each side",
  "exercise_9_title": "Press Up",
  "exercise_9_text":
      "1. There are toe press ups and knee press ups. The second is considred easier.\n\n2. Keeping your body in a straight line and your elbows close to your body, bend and straighten your arms to complete a press-up.\n\n3. If the first option is difficult, bend your knee and do the same as in the first exercise.\n\n4. Do 15 press-ups",
  "exercise_10_title": "Hand stretching",
  "exercise_10_text":
      "1. Extend your arms with your palms facing up toward the ceiling.\n\n2. Exhale as you extend your arms toward the ceiling.\n\n3. Inhale as you stand on the heel and relax.\n\n4. Repeat up to 5 times, each time extend your hands for 10 seconds.",
  "fitness": "FITNESS",
  "fitness_title":
      "Prepare for exercises which\n will restore your physical\n health",
  "good_morning": "Good morning",
  "good_afternoon": "Good afternoon",
  "good_evening": "Good evening",
  "good_night": "Good night",
  "meditation": "MEDITATION",
  "meditation_title":
      "Sit in a comfortable position,\n focus on your breathing.",
  "meditation_select": "Choose a Meditation",
  "meditation_menu_1": "Silence",
  "meditation_menu_2": "Only music",
  "meditation_menu_3": "Guided meditation",
  "note": "NOTE",
  "fitness_program": "Pre-made program",
  "fitness_my_program": "Make my program",
  "visualization": "VISUALIZATION",
  "visualization_title":
      "Close your eyes, imagine your desire, touch it, feel it, picture your way to it step by step ",
  "visualization_hint": "Type your visualization, briefly describe it",
  "diary": "DIARY",
  "voice_record": "A voice record",
  "written_record": "A written record",
  "affirmation": "AFFIRMATION",
  "affirmation_title":
      "Pronounce clearly, out loud,\n with full confidence and\nconcentration",
  "your_name": "Your name",
  "google": "Sign in with Google",
  "apple": "Sign in with Apple",
  "restart": "Restart",
  "menu": "Menu",
  "day": "Day",
  "min": "min",
  "sec": "sec",
  "pull_program": "To set up your program pull\n down exercises from above",
  "add_exercises": "Add\nexercises",
  "success": "Success!",
  "vip_restored": "Subscriptions restored",
  "pages": "How many pages ?",
  "continue": "Continue",
  "change_tarif": "Change tarif",
  "reminders": "Reminders",
  "add_first_reminder": "Add your first reminder",
  "select_week_day": "Select days of the week",
  "set_reminders": "Set a reminder",
  "stop": "Stop",
  "push_success": "Successfully!",
  "action_completed": "action completed!",
  "timer_started": "Timer\nstarted",
  "appreciate":
      "We appreciate your coziness and comfort, and therefore made the application paid. So that you can not be distracted by advertising.",
  "subscribe_futures":
      "Subscription will provide the opportunity to perform exercises such as: Fitness, Diary, Reading and Visualization. It renews automatically every month, but you can cancel it at any time.",
  "price": "Price",
  "tarif_month_title": "@days days free",
  "tarif_month_desc": "then - @price per month",
  "tarif_annual_title": "@price per year",
  "tarif_annual_desc": "@price per month",
  "well_done": "Well done!",
  "well_done_desc":
      "You have a great start to your morning, thank yourself and spend this day with benefit.",
  "buy_month": "Pay for subscription",
  "buy_free": "TRY THE FULL COMPLEX",
  "days_free": "@days days free",
  "buy_days": "Try @days days for free",
  "sure": "Are you sure ?",
  "sure_delete": "Are you sure you want to delete the exercise?",
  "cancel": "Cancel",
  "skip": "Skip",
  "minutes": "minutes",
  "choose_sequence": "Choose\nsequence",
  "choose": "Choose",
  "done": "Done",
  "choose_title":
      "Drag and drop to change sequence of exercises and set time on them.\n0 min - skip exercise.",
  "exercises_note": "Exercises",
  "visualizations_note": "Visualization",
  "seconds": "seconds",
  "affirmation_small": " Affirmations",
  "affirmation_smal": "Affirmations",
  "meditation_small": "Meditation",
  "fitness_small": "Fitness",
  "diary_small": "Diary",
  "menu_diary_small": "Diary",
  "Save the Affirmation": "Save the Affirmation",
  "or": "or",
  "Affirmation Settings": "Affirmation Settings",
  "menu_diary_desc": "Write down important thoughts in diary",
  "reading_small": "Reading",
  "visualization_small": "Visualization",
  "fitness_desc": "Tone yourself up with fitness",
  "visualization_desc": "Visualize your success",
  "reading_desc": "Get inspired by books in the morning",
  "duration": "Duration of",
  "complex": "complex: ",
  "magic_morning": "“Wonderful Morning”",
  "write_affirmation": "Write your\naffirmation",
  "affirmation_hint": "Write your Affirmation...",
  "book_name": "Write name\nof book",
  "input_cat_name": "Input category name",
  "input_desc": "Input a description",
  "player_voice": "Voice",
  "female": "Female",
  "male": "Male",
  "complexs": "complex",
  "language": "Language",
  "Add a reminder": "Add a reminder",
  "Are you sure you want to leave the complex":
      "Are you sure you want to leave the complex",
  "x_minutes": "@x min",
  "Monday": "Monday",
  "Tuesday": "Tuesday",
  "Wednesday": "Wednesday",
  "Thursday": "Thursday",
  "Friday": "Friday",
  "Saturday": "Saturday",
  "Sunday": "Sunday",
  "leave": "Leave",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "Mayi": "May",
  "June": "June",
  "July": "July",
  "August": "August",
  "September": "September",
  "October": "October",
  "November": "November",
  "December": "December",
  "Are you sure you want to delete a note?":
      "Are you sure you want to delete\n a note?",
  "How much time are you going to read?":
      "How much time are you going to read?",
  "Delete a note": "Delete a note",
  "add_exercise": "Add exercise",
  "Organize your morning routine with ease using the complex program":
      "Organize your morning routine\nwith ease using the complex program.",
  "name": "Name",
  "komplex": "Complex - ",
  "Customize the sequence and duration of your rituals in the":
      "Customize the sequence and duration of your rituals in the",
  "Settings section": " Settings section",
  "is a consistent set of your morning daily rituals. ":
      "is a consistent\n set of your morning\n daily rituals. ",
  "please_input_name": "Please enter your name",
  "delete_exercise": "Delete exercise",
  "delete_hint": "Clamp and hold\n to delete",
  "your_exercise": "Your exercise",
  "enter_your_exercise": "Enter your exercise",
  "add_permission": "Grant permission to record audio",
  "yes": "Yes",
  "For instance": "For instance:",
  "1) Meditation - 5 minutes2) Fitness & Yoga - 15 minutes 3) Reading - 20 minutes":
      "1) Meditation - 5 minutes\n2) Fitness & Yoga - 15 minutes \n3) Reading - 20 minutes",
  "no": "No",
  "other": "Other",
  "save_diary": "Save a note",
  "Start reading": "Start reading",
  "Start affirmation": "Start affirmation",
  "mornings": "Morning ",
  "enter_your_name": "Enter your name",
  "remove_progress": "Remove progress",
  "sure_delete_progress":
      "Are you sure you want to delete all the application progress ?",
  "and": " and ",
  "agreement_start": "By clicking “Next”, you confirm that you accept",
  "agreement_title": "Terms",
  "privacy_title": "Privacy policy",
  "paragraph1": "Write important thoughts in notes",
  "paragraph2": "Tone yourself up with fitness",
  "paragraph3": "Get inspiration from books in the morning",
  "paragraph4": "Visualize your success",
  "try_vip_desc":
      "Try it for @days days for free and then the price will be @price per month. \n\nYou can cancel your subscription at any time",
  "vip_price_card": "1 month",
  "vip_def_month_price": "0.99 \$",
  "for_confidence": "For confidence",
  "for_health": "For health",
  "for_love": "For love (Female)",
  "for_success": "For success",
  "for_career": "For career",
  "for_wealth": "For wealth",
  "confidence_text_1": "Challenges are opportunities to grow and improve",
  "confidence_text_2": "I believe in my abilities",
  "confidence_text_3": "There are no blocks I cannot overcome",
  "confidence_text_4": "I am worthy of living my life and having what I want",
  "confidence_text_5":
      "I allow myself to choose my own way, fulfilling my dreams",
  "confidence_text_6": "I love who I am inside and out",
  "health_text_1":
      "My body knows how to heal itself. I allow the intelligence of my body to move my health forward",
  "health_text_2":
      "I believe in my intuition. I always listen to my inner voice",
  "health_text_3":
      "I fall asleep easily. My body, mind, and soul are worthy of their rest",
  "health_text_4":
      "I am in harmony with my inner part, which knows secrets of healing",
  "health_text_5": "I become healthier and stronger everyday",
  "health_text_6": "I have much energy and vital power",
  "health_text_7":
      "I am in control of the mental atmosphere I create. Thoughts can be changed and the positive thoughts I choose are helping me heal",
  "health_text_8": "I am healthy, happy and radiant",
  "health_text_9": "I am worthy of good health",
  "health_text_10": "I radiate good health",
  "love_text_1": "I give my heart, ready to receive the heart of another",
  "love_text_2": "I feel I am loved",
  "love_text_3": "I deserve love and affection",
  "love_text_4": "I am terrifically charismatic",
  "love_text_5": "I give permission to my inner goddess to work her magic",
  "love_text_6": "I embrace being a woman",
  "love_text_7": "I am confident in my sexuality",
  "love_text_8":
      "I am open to a healthy, loving relationship that is right for me",
  "love_text_9": "I am worthy of accomplishment, success, and abundance",
  "love_text_10": "I am worthy of a healthy, loving relationship",
  "love_text_11":
      "I am in a wonderful relationship with someone who treats me right!",
  "success_text_1":
      "I am open-minded and always eager to explore new avenues to success",
  "success_text_2":
      "I have the power to create all the success and prosperity I desire",
  "success_text_3": "I am organised and manage my time well",
  "success_text_4": "I fly high and I always match my expectations",
  "success_text_5": "I trust my intuition and I always make wise decisions",
  "success_text_6":
      "I successively attract needed circumstances at the right time",
  "success_text_7":
      "Every day I am filled with new ideas which motivate and insipre me",
  "success_text_8": "I have unlimited power to achieve everything I want",
  "success_text_9": "I make smart decisions with joy",
  "success_text_10": "The Universe wants to help me, giving everything I need",
  "success_text_11": "I have the courage to use all the prizes of life",
  "career_text_1": "I am motivated, goal-oriented and self-consistent",
  "career_text_2": "I always achieve my career goals",
  "career_text_3": "Success at work is easy",
  "career_text_4": "I am respected and well treated",
  "career_text_5":
      "Right this moment, my resume is being seen by all the right people",
  "career_text_6":
      "I deserve a job that fulfills me and now I am ready to find it!",
  "career_text_7":
      "As I align my career with my true talents, the money and the happiness flows to me!",
  "career_text_8": "I work hard! I work smart! I deserve the accolades I earn!",
  "career_text_9": "Today and every day, I use my talents in satisfying ways!",
  "career_text_10": "I mold my career to my goals!",
  "career_text_11": "I am financially secure, doing what I want",
  "wealth_text_1": "I naturally attract good fortune",
  "wealth_text_2": "Money is my friends",
  "wealth_text_3": "I easily spend and get money!",
  "wealth_text_4": "I am a money magnet! Money flows freely to me",
  "wealth_text_5":
      "I have a positive relationship to money and know how to spend it wisely",
  "wealth_text_6":
      "I see the opportunities to attract money! I convert the best opportunities!",
  "wealth_text_7": "I am connected to the universal supply of money",
  "wealth_text_8": "The Universe showers me with gifts",
  "wealth_text_9": "Every good deed comes back to me multiplied",
  "wealth_text_10": "I always attract lots of resources and ideas",
  "start_program": "Start program",
  "program_settings": "Program settings",
  "restore_default": "Restore\ndefaults",
  "create_yours": "Create\nyour",
  "restore": "Restore subscription",
  "delete": "Delete",
  "edit": "Edit",
  "cancellation": "Cancel",
  "exercises": "Exercises",
  "add_yours": "Create yours",
  "save": "Save",
  "delete_program_alert": "Are you sure you want to delete a program?",
  "initial_exercises_empty":
      "Default exercises are already added\n Try to make your own exercise",
  "restore_default_dialog_title":
      " Are you sure you want to restore default exercises?\nUser programs/exercises will be deleted",
  "name_not_be_empty": "A name can not be empty",
  "type_exercise_name": "Type an exercise name",
  "type_program_name": "Type a program name",
  "type_exercise_description": "Type an exercise description",
  "hold_to_move_exercise": "Hold to move an exercise",
  "type_name": "Type a name",
  "tutorial_text": "How easy is it to get up in the morning?",
  "rate_app_title": "Rate app",
  "rate_app_description": "Your rating will help us become better",
  "action_rate": " Rate",
  "action_remind": "Remind me later",
  "rate_subject": "App rating",
  "my_progress": "MY PROGRESS",
  "Try PREMIUM": "Try PREMIUM",
  "3 days free": "3 days free",
  "Finish reading": "Finish reading",
  "exercise_complete": "Exercise complete",
  "affirmation_timer": "Affirmations",
  "audio_loading": "Audio is loading...",
  "success_target": "Success",
  "family_target": "Family",
  "nature_target": "Nature",
  "rest_target": "Rest",
  "sport_target": "Sport",
  "target_selection": "Select target",
  "remove_created_target": "Remove created target?",
  "impression_selection": "Select impression",
  "remove_image": "Remove image?",
  "target_title": "title",
  "target_short_desc":
      "in the field describe briefly (in one sentence) what you will visualize",
  "music_menu_music": "Music",
  "music_menu_sounds": "Sounds",
  "music_menu_meditations": "Meditations",
  "music_menu_favorite": "Favorite",
  "purchase_page_title": "Discover the morning in a new way",
  "purchase_page_desc": "@days days free",
  "go_start_record": "Click to start recording",
  "go_stop_record": "Recording in progress, click to stop",
  "empty_favorite_list": "You have no saved music",
  "purchase_bonuses_image": "assets/images/purchase/bonuses_en.png",
  "faq_menu_title": "Frequently asked Questions",
  "faq_cat_support": "Support",
  "faq_cat_why": "What is it for?\n",
  "faq_cat_tarifs": "Subscription questions",
  "faq_tarifs_title_1": "What does the subscription give?",
  "faq_tarifs_desc_1":
      "<p>-removes ads <br>- access to sections fitness, diary, reading, visualizations <br>- access to future new complexes.</p>",
  "faq_tarifs_title_2": "Why the app isn’t free?",
  "faq_tarifs_desc_2":
      "<p>- free goods aren’t appreciated, if you don’t invest in self-development tools, you won’t appreciate it <br>- all money what we receive from subscribers, we go to improve the application</p>",
  "faq_tarifs_title_3": "How to change a tariff?",
  "faq_tarifs_desc_3":
      "<p>1. Go to the <a href='screen:tarifs'>«tariff plan»</a> tab (you can click) <br>2. Select the needful tariff <br>3. Click change the tariff <br>4. Next month the tariff will change</p>",
  "faq_tarifs_title_4": "How to restore a subscription?",
  "faq_tarifs_desc_4":
      "<p>Recovery works only if you have an active subscription You can click on the \"restore subscription\" button Or do it manually <br>1. Go to the <a href='screen:tarifs'>«tariff plan»</a> tab (you can click) <br>2. Click on the bottom to restore</p>",
  "faq_tarifs_title_5": "How to cancel a subscription?",
  "faq_tarifs_desc_5":
      "<p>You can do it manually or click on the button <a href='screen:unsubscribe'>«Unsubscribe»</a></p>",
  "faq_tarifs_title_6": "Contact support",
  "faq_about_title_1": "What are these exercises for?",
  "faq_about_desc_1":
      "<p>Meditation - helps to awake the mind slowly and keep calm <br>Affirmations - charge the mind with positive emotions <br>Visualizations - allow you to accurately represent the wishful success <br>Fitness - energizes your body <br>Reading - education in the morning! (especially if there isn’t enough time in the evening) <br>Diary - remember what you did and what you learned, write down the most important thoughts <br>It’s better to devote an hour a day and engage in the whole complex, but performing at least a couple of practices will already have an effect.</p>",
  "faq_about_title_2": "How to use?",
  "faq_about_desc_2":
      "<p>Start with the \"settings\" there you can set: <br>-Time of each practice <br>-The sequence of the complex <br>- Affirmation by default <br>- The book which you are reading <br>The settings can be changed at any time. <br>After you configure, you can click the \"start\" button, everything will happen in accordance with the selected settings</p>",
  "faq_about_title_3": "Why use?",
  "faq_about_desc_3":
      "<p>Practicing will help you tune in for the day, charge you with a cheerfulness and help get rid of stress <br>Many top managers and successful people choose to wake up earlier in order to achieve better results. However, it is also useful if you just want to recharge your energy or improve your mental attitude.</p>",
  "faq_about_title_4": "When I see the result?",
  "faq_about_desc_4":
      "<p>After 10 days, it will be possible to develop a habit <br>After a month of using, you will be able to feel that it has become much easier to wake up, and stress has become noticeably less.</p>",
  "faq_about_title_5": "How to set up fitness?",
  "faq_about_desc_5":
      "<p>1. Click on <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F02-min%20(1).png?alt=media&token=5f53f785-9dd5-4a46-957e-0f8a7dca7f62' width='25' /> in settings <br>2. Select the program you want to edit <br>3. Click edit <br>There is a problem? <a href='screen:support'>support</a></p>",
  "faq_about_title_6": "How to set up visualizations?",
  "faq_about_desc_6":
      "<p>1. To add a target, click on the <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F01-min.png?alt=media&token=17783548-ef94-40ed-87ed-db6a3979e0ac' width='25' /> in the target selection <br>2. Then select the image from those saved in your phone <br>3. Wait while the pictures are loaded <br>4. You can use ready-made goals and images, or add your own images to goals using the same instructions. <br>There is a problem? <a href='screen:support'>support</a></p>",
  "welcome_to_sleep": "Welcome to Sleep",
  "meditation_subtitle": "Listen to one of our meditations to relieve stress",
  "music_for_sleep_subtitle": "Fall asleep with your favorite music",
  "music_for_sleep_title": "Sleep sounds",
  "reading_at_night_title": "Reading at night",
  "reading_at_night_subtitle": "If you prefer to read before bed",
  "music_instrument_title": "Musical instruments",
  "instrument_1": "Harp",
  "instrument_2": "Glucophone",
  "instrument_3": "Harmonica",
  "instrument_4": "Wooden spoons",
  "instrument_5": "Lullaby",
  "Do you have trouble": "Do you have trouble\n",
  "What do you want to ": "What do you want ",
  "concentrating?": "concentrating?",
  "to get out of My Morning?": "to get\nout of My Morning?",
  "instrument_6": "Piano",
  "instrument_7": "Violin",
  "instrument_8": "The flute",
  "music_instrument_places": "Places",
  "onb3p1": "Continue",
  "place_1": "In the cafe",
  "place_2": "Village",
  "place_3": "Train",
  "place_4": "The flow of cars",
  "place_5": "Airplane",
  "place_6": "Construction",
  "place_7": "Crowd",
  "music_instrument_other": "Other",
  "other_1": "Fan",
  "other_2": "Auto wipers",
  "other_3": "Keyboard",
  "other_4": "Bells",
  "other_5": "Heart",
  "other_6": "Watch",
  "music_instrument_sound_of_nature": "Sounds of nature",
  "nature_1": "Wind in the grass",
  "nature_2": "Waterfall",
  "nature_3": "Blizzard and snow",
  "nature_4": "Thunder",
  "nature_5": "Rain and umbrella",
  "nature_6": "Rain and tent",
  "nature_7": "Rain in a puddle",
  "nature_8": "Thunderstorm",
  "nature_9": "Rain",
  "nature_10": "Dripping",
  "nature_11": "Downpour",
  "nature_12": "Fire",
  "nature_13": "Lake",
  "nature_14": "Ocean",
  "nature_15": "Underwater",
  "nature_16": "Stream",
  "nature_17": "Strong wind",
  "nature_18": "Snow crunch",
  "nature_19": "Rustle of Grass",
  "music_instrument_living_creatures": "Living things",
  "creatures_1": "Whale",
  "creatures_2": "Cat lapping milk",
  "creatures_3": "Horse gallop",
  "creatures_4": "The horse is coming",
  "creatures_5": "Frog",
  "creatures_6": "Frogs",
  "creatures_7": "Cat Purr",
  "creatures_8": "Birds",
  "creatures_9": "Birds 2",
  "creatures_10": "Crickets",
  "creatures_11": "Owl",
  "creatures_12": "Seagull",
  "save_selected": "Save Selected",
  "my_night": "My night",
  "onb_1_text_1":
      "Hello!@dI am your mentor and I am going to make your morning perfect.",
  "onb_1_btn": "How are you going to help me?",
  "onb_2_text_1":
      "My job is@dto bring everyday chaos under control and to create a perfect system that will fundamentally change your life.",
  "onb_2_btn": "How are we going to do it?",
  "onb_3_text_1":
      "Every morning@dyou will begin with a certain set of habits and rituals. They will give you the charge of vivacity, energy and motivation for the whole day!",
  "onb_3_btn": "How is it going to change my life?",
  "onb_4_btn": "Nice! Can you tell me about the habits?",
  "onb_5_text_1":
      "Power is in small steps!@dEvery day you will be creating your life step by step, piece by piece. I guarantee that in two months you won't recognize yourself!",
  "onb_6_text_1": "Habit No. 1",
  "onb_6_text_2": "Morning exercises",
  "onb_6_text_3":
      "Everyone knows, but no one does!@dBut if you do it right, it's much more powerful than coffee and the most effective way to invigorate and finally wake up!",
  "onb_6_text_4":
      "Get ready for a set of special exercises that in 5 minutes will give you a surge of energy and boost for the whole day!",
  "onb_6_btn": "Habit No. 2",
  "onb_7_text_1": "Habit No. 2",
  "onb_7_text_2": "Reading",
  "onb_7_text_3":
      "There is never time for it!@dAnd that is why morning is the perfect time to read educational literature while everyone is asleep!",
  "onb_7_text_4":
      "I will help to make sure you read a little, but every day. Remember - power is in small steps!",
  "onb_7_btn": "Habit No. 3",
  "onb_8_text_1": "Habit No. 3",
  "onb_8_text_2": "Planning",
  "onb_8_text_3":
      "To have a productive day@dyou need to know what to do! And in this regard we're going to write your plan for the day every morning.",
  "onb_8_text_4":
      "You will write down or record in audio format your plans and goals, as well as your thoughts and ideas right in the app.",
  "onb_8_btn": "Habit No. 4",
  "onb_9_text_1": "Habit No. 4",
  "onb_9_text_2": "Meditations",
  "onb_9_text_3":
      "Clear your mind from unnecessary thoughts.@dMeditation is one of the most viable practices. It immediately affects you and this effect accumulates every time.",
  "onb_9_text_4":
      "Meditations are embedded into the application. We have thought everything through - just turn on and practice!",
  "onb_9_btn": "Habit No. 5",
  "onb_10_text_1": "Habit No. 5",
  "onb_10_text_2": "Affirmations",
  "onb_10_text_3":
      "Have you been dreaming about@dsomething for a long time? The practice of affirmations allows you to reprogram your subconscious mind and set it up to fulfill your goals and desires.",
  "onb_10_text_4":
      "Embedded affirmations system will let you to practice naturally and effectively.",
  "onb_10_btn": "What else?",
  "onb_11_text_1": "Full statistics",
  "onb_11_text_2":
      "Detailed statistics of all habits, so you could monitor your progress",
  "onb_11_text_3": "So, are you ready to change your life?",
  "onb_11_btn": "I'm ready! Let's go!",
  "paywall_title": "Try@d MY MORNING@d\nFOR FREE",
  "popular": "Popular",
  "profitable": "Profitable",
  "cancel_subscribe_any_time": "Cancellation at any time",
  "text": "Text",
  "your_own_ritual": "Your own ritual",
  "support_text_title": "Take the Survey",
  "support_text_body": "And help the development of the application.",
};
