Map<String, String> translations_ge = {
  'onb_3_1_title': 'Wenn nicht jetzt,\n     wann dann?',
  'onb_3_1_subtitle':
      '         Beginne damit, dich um dich selbst zu\n         kümmern und Gewohnheiten für den\n         Morgen zu entwickeln,die dein Leben für\n                   immer verändern werden',
  'onb_3_2_title_1': 'Um wie viel Uhr wachst du\n',
  'onb_3_2_title_2': 'normalerweise auf?',
  'onb_3_3_title_1': 'Neigst du dazu,\n',
  'onb_3_3_title_2': 'Dinge aufzuschieben?',
  'onb_3_3_item_1_name_1': 'Ja, und ',
  'onb_3_3_item_1_name_2': 'das möchte\nich ändern',
  'onb_3_3_item_2_name_1': 'Nein, ',
  'onb_3_3_item_2_name_2': 'ich kann mich gut an\nmeinen Plan halten',
  'onb_3_3_item_3_name_1': "Ich bin ",
  'onb_3_3_item_3_name_2': 'mir nicht sicher',
  'onb_3_4_title_1': 'Fällt es dir schwer, dich zu\n',
  'onb_3_4_title_2': 'konzentrieren?',
  'onb_3_4_item_1_name_1': 'Ja, ',
  'onb_3_4_item_1_name_2': 'ich lasse mich leicht\nablenken',
  'onb_3_4_item_2_name_1': 'Nein, ',
  'onb_3_4_item_2_name_2':
      "ich kann mich gut\nkonzentrieren und lasse\nmich nicht ablenken",
  'onb_3_4_item_3_name_1': "Ich ",
  'onb_3_4_item_3_name_2': 'bin mir nicht sicher',
  "nexting": "Continue",
  'onb_3_5_title_1': 'Was willst ',
  'onb_3_5_title_2': 'du mit\nMy Morning erreichen?',
  'onb_3_5_item_1_name_1': 'Ich möchte ',
  'onb_3_5_item_1_name_2': 'gute Gewohnheiten\nentwickeln',
  'onb_3_5_item_2_name_1': 'Ich möchte ',
  'onb_3_5_item_2_name_2': "meinen Tag\nbesser planen",
  'onb_3_5_item_3_name_1': "Ich bin ",
  'onb_3_5_item_3_name_2': 'mir nicht sicher',
  "lets go": "Los geht's!",
  "subscription": "Abonnement",
  "settings_desc": "Richte deinen Komplex ein",
  "start_complex": " Komplex starten",
  "set_timer": "Timer einstellen",
  "dont_add_time": "Zeit nicht ändern",
  "select": "Auswählen",
  "Continue": "Weiter",
  "How much": "Wie viel Schlaf ",
  "sleep": "bekommst\n",
  "do you usually get at hight": "du normalerweise nachts? ",
  "Morning": "Morgen",
  "hours": " Stunden",
  "hours or": "Stunden ",
  "less": "oder weniger",
  "more": "more",
  "Evening": "Abend",
  "Unlock all features": "   Erstelle deine perfekte\n          Morgenroutine",
  "Build your perfect morning routine":
      "Erstellen Sie Ihre perfekte Morgenroutine",
  "Got it! Do you": "Verstanden! Fühlst du ",
  "wake up": "dich\nbeim ",
  "feeling well-rested?": "Aufwachen ausgeruht?",
  "Always": "Immer",
  "Usually": "Normalerweise",
  "Sometimes": "Manchmal",
  "High ": "Hoch",
  "Medium ": "Mittel ",
  "meditation is complete": "Die Meditation ist abgeschlossen",
  "Low ": "Niedrig ",
  "- energized troughot the day": "- den ganzen Tag über voller Energie",
  "- i have bursts of energy": "- ich habe Energieschübe",
  "- my energy fades troughout the day":
      "- meine Energie lässt im Laufe des Tages nach",
  "How satisfied are you with your ": "Wie zufrieden bist du\nmit deinem ",
  "current fitness level?": "aktuellen\nFitnesslevel?",
  "Completeli ": "Vollkommen ",
  "Somewhat ": "Einigermaßen ",
  "Not at all ": "Überhaupt nicht ",
  "- I feel fit and healthy": "- Ich fühle mich fit und gesund",
  "- I'd like to see some                 improvement":
      "- ich würde mich gerne\n                      verbessern",
  "- I'd like to see a major change":
      "- ich würde gerne eine größere\n                          Veränderung sehen",
  "Over the past year, what's been ": "Welche Erfahrungen hast\n",
  'your experience': 'du im letzten Jahr gemacht,\n',
  " building better habits?": "um deine Gewohnheiten zu verbessern?",
  "I have been ": "Ich habe meine ",
  "I have built ": "Ich habe einige ",
  "I have tried t build good habits,":
      "Ich habe versucht, mir gute\nGewohnheiten anzueignen,\n",
  "I have not tried ": "Ich habe nicht versucht,",
  "constantly improving my habits": "Gewohnheiten\nständig verbessert",
  "some good habits": "gute Gewohnheiten\nentwickelt",
  "but have not kept up with them": "habe sie aber nicht beibehalten",
  "to build new habits": " neue\nGewohnheiten zu entwickeln",
  "Rarely": "Selten",
  "7one": "",
  "7two": "",
  "7tree": "",
  "7four": "",
  "More  ": "Mehr  ",
  "energy": "Energie",
  "productivity": "Produktivität",
  "mindfulness": "Achtsamkeit",
  "Sleep": "Schlaf",
  "We hear you. What single change ": "Wir verstehen dich.Welche einzige\n",
  "would improve your life right now?":
      "Veränderung würde dein\n  Leben jetzt verbessern?",
  "8tree": "",
  "How often ": "Wie oft konzentrierst ",
  "do you focus": "du dich\nauf die ",
  "on the past or futue?": "Vergangenheit\n    oder die Zukunft?",
  "Never ": "Nie ",
  "Some ": "Ab ",
  "Most ": "Meistens ",
  "All ": "Die ",
  "of the time1": "und zu",
  "of the time2": "",
  "of the time3": "ganze Zeit",
  "How ": "Wie ",
  " are you?": " du ablenkbar?",
  "distractable": "leicht bist\n",
  "Easily ": "Leicht ",
  "Sometimes ": "Manchmal ",
  "Rarely ": "Selten ",
  "Laser ": "Scharfsinnig ",
  "distracted": "ablenkbar ",
  "lose focus": "unkonzentriert",
  " focus": " ",
  "You're embarking on this journey ": "Du begibst dich auf\n diese Reise, ",
  "to build more Energy": "um mehr\nEnergie aufzubauen ",
  "Fitness": "Fitness",
  "Visualization": "Visualisierung",
  "/month,\ncancel anytime": "/monat,\nJederzeit\nkündigen",
  "/year,\ncancel anytime": "/jahr,\nJederzeit\nkündigen",
  ", one-\ntime payment": ", Einmal\nige Zahlung",
  "Monthly": "Monatlich",
  "Annually": "Jährlich",
  "Lifetime": "Lebenszeit",
  "Restore": "Wiederherstellen",
  "Terms": "Geschäftsbedingungen",
  "Privacy": "Datenschutz",
  "month, cancel anytime": "/Monat,\njederzeit kündbar",
  "year, cancel anytime": "/Monat,\njederzeit kündbar",
  "one-time payment": ", einmalige Zahlung",
  "Start 3 days free trial": "3 Tage kostenlose Testversion starten",
  "Meditationse": "Meditationen",
  "your entire morning routine in one app":
      "Deine gesamte Morgenroutine in einer App",
  "Reading": "Lesen",
  "Just ": "Nur ",
  "Customize the sequence and duration of your rituals in the Settings section.":
      "Passen Sie die Reihenfolge und Dauer Ihrer Rituale im Bereich Einstellungen an.",
  "30 minutes every day for a year ": "30 Minuten jeden Tag für ein ",
  "will change your life dramatically!":
      "Jahr werden dein Leben\n dramatisch verändern!",
  "Ready": "Bereit\n",
  "to start?": "anzufangen?",
  "Notes": "Notizen",
  "Affirmations": "Bestärkungen",
  "We’re finalizing your personalized journey...":
      "Wir schließen deine\npersönliche Reise ab...",
  "I live in the present": "- ich lebe in der Gegenwart",
  "minutes": "minutes",
  "How much time ": "Wie viel Zeit ",
  "Understood! Throughout your day, how are your":
      "Verstanden! Wie ist dein\nEnergielevel über den\n",
  "energy levels": " Tag verteilt?",
  "energy levels two": "",
  "do you have ": "hast du\n",
  "at the start of your day?": "zu Beginn deines Tages?",
  "Change your life with": "Verändere dein Leben mit\n",
  "morning rituals": "morgendlichen Ritualen",
  "Set your own time": "Bestimmen Sie Ihre eigene Zeit",
  "Statistics": "Statistik",
  "Notifications": "Benachrichtig",
  "How much time are you going to read":
      "Wie viel Zeit werden Sie für das Lesen?",
  "own_time": "Eigene Zeit",
  "1_hour": "1 Stunde",
  "Choose an affirmation": "Wählen Sie eine Bestärkungen",
  "input your name": "Eingabe Ihres Namens",
  "thanks_to_interview": "Vielen Dank, wir werden dir auf jeden Fall zuhören!",
  "help_us": "Hilf uns",
  "Complete": "Vollständig",
  "Add note": "Notiz hinzufügen",
  "Save note": "         Notiz speichern         ",
  "Recording paused": "Aufnahme pausiert",
  "Mindful minutes per week": "Achtsame Minuten pro Woche",
  "Recording in progress": "Aufzeichnung in Arbeit",
  "Write something here..": "Schreiben Sie hier etwas..",
  "more_not_show": "Nicht mehr anzeigen",
  "interview_dialog_text":
      "Hey! Willst du 14 Tage lang kostenlos testen? Dann nimm an der Umfrage teil und hilf uns, diese App zu verbessern!",
  "interview_dialog_text_vip":
      "Hey! Danke, dass du die Vollversion der Anwendung benutzt. Wir wollen sie besser machen, deshalb sind wir dir für die Umfrage dankbar.",
  "question_1":
      "Machen wir uns miteinander bekannt. Erzähl mir etwas über dich: Alter, Geschlecht, Land (optional)",
  "question_2": "Fällt es dir schwer, morgens aufzuwachen?",
  "question_2_subquestion_1": "Wenn ja, warum?",
  "question_3":
      "Benutzt du Apps, um deine geistige und körperliche Gesundheit zu verbessern?",
  "question_3_subquestion_1": "Wenn ja, welche?",
  "question_4": "Gefallen dir unsere kostenlosen Funktionen?",
  "question_5": "Warum hast du dich für unser Produkt entschieden?",
  "question_6":
      "Was hast du gebraucht, als du nach unserem Produkt gesucht hast?",
  "question_7": "Hast du gefunden, wonach du gesucht hast?",
  "question_8": "Welchen Nutzen hast du von unserer App?",
  "question_9": "Welche Funktionen brauchst du?",
  "question_10":
      "Was würdest du hinzufügen? Was würdest du entfernen? Was würdest du ändern?",
  "question_11":
      "Ist es deiner Meinung nach eine gute Idee, Tagesübungen einzuführen?",
  "question_11_subquestion_1": "Wenn ja, welche? (Atmung, Fitness am Tag)",
  "question_12":
      "IIst es deiner Meinung nach eine gute Idee, Nachtübungen einzuführen?",
  "question_12_subquestion_1":
      "Wenn ja, welche? (Schlafgeräusche, Schlafvorbereitung)",
  "question_13":
      "Wenn du an einem Interview mit uns teilnehmen möchtest, hinterlasse bitte deine E-Mail-Adresse für die weitere Kommunikation.",
  "interview_2_q_1":
      "Machen wir uns bekannt. Erzähl mir etwas über dich: Alter, Geschlecht, Land (optional)",
  "interview_2_q_2": "Hat die App deine Erwartungen nicht erfüllt? Warum",
  "interview_2_q_3": "Haben dir unsere kostenlosen Funktionen gefallen??",
  "interview_2_q_4": "Welchen Nutzen hast du von unserer App gehabt?",
  "interview_2_q_5": "Welche Funktionen hältst du für notwendig?",
  "interview_2_q_6":
      "Was würdest du hinzufügen? Was würdest du entfernen? Was würdest du ändern?",
  "interview_2_q_7":
      "Ist es deiner Meinung nach eine gute Idee, Tagesübungen einzuführen?",
  "interview_2_q_7_sub_1": "Wenn ja, welche? (Atmung, Fitness am Tag)",
  "interview_2_q_8":
      "Ist es deiner Meinung nach eine gute Idee, Nachtübungen einzuführen?",
  "interview_2_q_8_sub_1":
      "Wenn ja, welche? (Schlafgeräusche, Schlafvorbereitung)",
  "interview_2_q_9":
      "Wenn du an einem Interview mit uns teilnehmen möchtest, hinterlasse bitte deine E-Mail-Adresse für die weitere Kommunikation",
  "please_fill_all_fields": "Bitte fülle alle Felder aus",
  "lets_acquainted": "Lass uns Bekanntschaft schließen",
  "welcome_page_title": "Schön, dich kennenzulernen!",
  "welcome_page_subtitle":
      "Diese Anwendung ist für deinen Komfort gedacht. Kurze Meditationslektionen und andere Komplexe werden dir helfen, dem Morgen mit Elan zu begegnen, Stress abzubauen, dich auf den Tag einzustimmen und nachts besser zu schlafen.",
  "welcome_push_title": "Wann möchtest du aufwachen?",
  "welcome_push_subtitle":
      "Wähle die Zeit aus, und wir sorgen dafür, dass du nicht verschlafen wirst",
  "start_input": "Fang an zu schreiben ...  ",
  "start": "Start",
  "progress_item": "Fortschritt",
  "settings": "Einstellungen",
  "pay": "Abonnement kaufen",
  "store_app": "Shop",
  "user_is_pro": "Abo",
  "tarif_plans": "Tarifplan",
  "tarif_plans_done": "Abo",
  "upsell_screen": "Vorbestellung",
  "loading_buy": "Laden",
  "loading_buy_app_bar": "Laden...",
  "start_fitness_my_program": "Dein Programm starten",
  "awareness_meter": "Bewusstseinsmesser",
  "month": "Monat",
  "year": "Jahr",
  "total": "Gesamt",
  "for_week": "Für die Woche",
  "skip_note": "überspringen",
  "skip": "Überspringen",
  "pages_note": "Seiten",
  "pages_short": "Seiten",
  "minutes_per_week": "Minuten",
  "monday_short": "mo",
  "have_not_sub": "Du bist nicht angemeldet",
  "no_sound": "Kein Ton",
  "tuesday_short": "di",
  "wednesday_short": "mi",
  "thursday_short": "do",
  "tutorial_asset": "assets/audios/tutorial_eng.mp3",
  "friday_short": "fr",
  "saturday_short": "sa",
  "sunday_short": "so",
  "count_of_sessions": "Anzahl der\nnabgeschlo\nssenen\nÜbungen",
  "minutes_of_awareness_with_myself":
      "Minuten der\n Achtsamkeit\nmit mir\nselbst",
  "count_of_completed_sessions": "Anzahl\nabges\nchlossener\nKomplexe",
  "my_diary": "Mein Tagebuch",
  "my_exercises": "Meine Übungen",
  "my_affirmations": "Meine Bestärkungen",
  "my_books": "Meine Bücher",
  "my_visualization": "Meine Visualisierungen",
  "choose_ready": "Wähle eine aus",
  "add_note": "Notiz hinzufügen",
  "PREMIUM activated": "PREMIUM aktiviert",
  "Add your": "Fügen Sie Ihr",
  "Start": "Lesen beginnen",
  "Starting": "Beginnen",
  "Try PREMIUM Package for free": "PREMIUM-Paket kostenlos testen",
  "Choose favorite meditations": "Lieblingsmeditationen\nauswählen",
  "Finish meditating": "Meditieren beenden",
  "5 min": "5 minutes",
  "10 min": "10 minutes",
  "min 1": "minutes",
  "2 min": "2 minutes",
  "3 min": "3 minutes",
  "Fitnes": "Fitness",
  "Edit": "bearbeiten",
  "15 min": "15 minutes",
  "Favorites": "Favoriten",
  "Meditations": "Meditationen",
  "You haven't added any meditations to your favorites":
      "Sie haben noch keine\nMeditationen zu Ihren\nFavoriten hinzugefügt",
  'Mon': 'Mon',
  'Tue': 'Die',
  'Wed': 'Mit',
  'Thu': 'Don',
  'Fri': 'Fre',
  'Sat': 'Sam',
  'Sun': 'Son',
  'Jan': 'Jan',
  'Feb': 'Feb',
  'Mar': 'März',
  'Apr': 'Apr',
  'May': 'Mai',
  'Jun': 'Juni',
  'Jul': 'Juli',
  'Aug': 'Aug',
  'Sep': 'Sep',
  'Oct': 'Oct',
  'Nov': 'Nov',
  'Dec': 'Dez',
  "faq": "FAQ",
  "reading": "LESEN",
  "reading_title":
      "Nimm eine bequeme Position ein und bereite dich auf ein Buch vor",
  "next_button": "Weiter",
  "progress": "FORTSCHRITT",
  "progress_title": "Du hast keinen schönen Morgen erlebt.",
  "back_button": "Zurück",
  "check internet connection": "Internetverbindung prüfen",
  "timer": "Timer",
  "exercise": "Übung @id",
  "listen_to": "Höre es dir an",
  "next_exercise": "Nächste Übung",
  "program_1": "Yoga. “Sonnengruß - Surya Namaskar”",
  "program_1_ex_1_name": "Hasta Uttanasana",
  "program_1_ex_1_desc":
      "-  Stehe aufrecht und hebe beide Hände über den Kopf. Die beiden Arme sollten schulterbreit auseinander liegen.\n- Das Heben der Arme und das Beugen des Rumpfes nach hinten werden gleichzeitig ausgeführt. Atme tief ein, während du die Arme anhebst.- \nStelle dich wieder in die Ausgangsposition.",
  "program_1_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHasta%20Uttanasana.mp3?alt=media&token=c010bab3-eb1f-4cd6-9199-d12b2836ed26',
  "program_1_ex_2_name": "Uttanasana",
  "program_1_ex_2_desc":
      "• Stellen Sie sich aufrecht hin und atmen Sie tief ein\n• Beim Ausatmen strecken Sie Ihren Oberkörper nach unten.\n• Bleiben Sie im Nacken lang, ohne den Rücken zu krümmen.",
  "program_1_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FUttanasana.mp3?alt=media&token=60ed84bd-c90e-4ffa-b5ac-f12990c4b613',
  "program_1_ex_3_name": "Ashwa Sanchalanasana",
  "program_1_ex_3_desc":
      "  - Komme in die nach unten gerichtete Hundestellung.\n- Atme aus und bringe dein rechtes Knie zu deiner Nase. Halte dein rechtes Knie in einem 90-Grad-Winkel gebeugt.\n- Hebe die Arme zum Himmel, senke das linke Knie ab und schiebe das rechte Knie zurück in die Tischposition oder stelle alternativ den rechten Fuß zurück in den Abwärtsgerichteten Hund.  ",
  "program_1_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAshwa%20Sanchalanasana.mp3?alt=media&token=adac340e-29b7-4b46-a2b5-4015c65c2a04',
  "program_1_ex_4_name": "Adho Mukha Svanasana",
  "program_1_ex_4_desc":
      "  - Stelle dich auf alle Viere, die Hände befinden sich etwa 5 cm vor den Schultern und sind schulterbreit auseinander.\n- Atme ein. Atme aus und begib dich in die nach unten gerichtete Hundestellung. Drücke mit den Fingerspitzen fest nach unten, um deine Unterarme nach vorne zu ziehen. Du kannst deine Knie beugen.\n- Gehe zurück in die Ausgangsposition.   ",
  "program_1_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAdho%20Mukha%20Svanasana.mp3?alt=media&token=2499d895-ebf7-44cd-8255-1b51d52a33b1',
  "program_1_ex_5_name": "Bhujangasana",
  "program_1_ex_5_desc":
      "1. Lege dich flach auf deinen Bauch.\n2. Lege deine Handflächen flach auf den Boden direkt unter deine Schultern.\n3. Atme ein und hebe deinen Brustkorb vom Boden ab. Halte dein Gesäß und deine Beine gestreckt.",
  "program_1_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBhujangasana.mp3?alt=media&token=fe0835bb-cca4-4141-9651-678c0fac3f28',
  "program_1_ex_6_name": "Gomukhasana",
  "program_1_ex_6_desc":
      "Beginne im sitzenden Schneidersitz, wie auf dem Bild zu sehen.\n- Atme ein und strecke deine Arme gerade nach oben zur Decke. Atme aus und verschränke die Hände hinter deinem Rücken.\n- Komme zurück in die Ausgangsposition und wechsle Beine und Arme ab.",
  "program_1_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FGomukhasana.mp3?alt=media&token=47a01e08-b6b7-4045-8aa9-733bc7a39fc2',
  "program_2": "Gute Stimmung",
  "program_2_ex_1_name": "Walk-in-Place",
  "program_2_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FWalk-in-Place.mp3?alt=media&token=0210ca41-b307-43bf-8e83-1e360d9b9422',
  "program_2_ex_1_desc":
      "•	Stand upright, arms at side \n•	Lift right leg, lower right leg; lift left leg, lower left leg",
  "program_2_ex_2_name": "Stehende Seitenbeuge",
  "program_2_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend.mp3?alt=media&token=51ad278d-44e8-49bc-9b11-99a5b8b074a4',
  "program_2_ex_2_desc":
      "- Stehe aufrecht mit schulterbreit auseinander stehenden Füßen und Beinen.\n- Senke deinen rechten Arm an der rechten Körperseite ab und atme aus, während du den linken Arm über den Kopf streckst und den Körper leicht nach rechts beugst. Atme aus, während du die Übung auf der linken Seite wiederholst.",
  "program_2_ex_3_name": "Kniebeugen mit Körperdrehung",
  "program_2_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20body-rotation.mp3?alt=media&token=418c6afc-3ec0-48b6-a6e8-6a36dc9ed335',
  "program_2_ex_3_desc":
      "-  Stehe gerade und stelle die Füße schulterbreit auseinander.\n- Mache eine Kniebeuge.\n - Dann drückst du dich durch die Fersen, um aufzustehen, und hebst die Arme über Kopf nach rechts. Verlagere das Gewicht auf die rechten Füße, die linken Füße auf die angehobenen Zehen.\n - Beuge die Knie in die Hocke und stehe zu einer anderen Seite auf.",
  "program_2_ex_4_name": "Balance",
  "program_2_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBalance.mp3?alt=media&token=2d14b8ed-bcda-4ee2-a56f-959e3203e8c9',
  "program_2_ex_4_desc":
      "-  Stehe aufrecht, Arme an der Seite. Hebe das rechte Bein an und beuge es.\n- Stell dich auf das linke Bein, strecke die Hände nach vorne und hebe das linke Bein hinter dich.\n- Halte die Position für einige Zeit und stehe gerade. \n- Stelle die Beine wieder auf.",
  "program_2_ex_5_name": "Brücke",
  "program_2_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBridge.mp3?alt=media&token=efbe555e-42b7-4673-b290-36c5b78ccb38',
  "program_2_ex_5_desc":
      "-  Leg dich auf den Rücken, die Hände an den Seiten, die Knie gebeugt und die Füße flach auf dem Boden unter den Knien.\n- Hebe deine Hüfte an, so dass eine gerade Linie von den Knien zu den Schultern entsteht. Spanne deine Bauch\n- und Gesäßmuskeln an. \n- Führe mindestens 20 Wiederholungen durch.",
  "program_3": "Berge versetzen",
  "program_3_ex_1_name": "Stehende Seitenbeugen ",
  "program_3_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend%20copy.mp3?alt=media&token=23112729-ce26-48d7-9bd6-66f7a86a404e',
  "program_3_ex_1_desc":
      "	- Stehe aufrecht mit schulterbreit auseinander stehenden Füßen und Beinen. \n- Lege deinen rechten Arm an die rechte Hüfte und atme aus, während du \nden linken Arm über den Kopf streckst und den Körper leicht nach rechts beugst. Atme aus, während du die Übung auf der linken Seite wiederholst.",
  "program_3_ex_2_name": "Kniebeugen mit Sprüngen",
  "program_3_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20Jumps.mp3?alt=media&token=8c827f9b-0cc8-4530-baf7-0e1a306f290f',
  "program_3_ex_2_desc":
      "	- Stehe mit den Fersen weiter als schulterbreit auseinander, die Zehen sind leicht nach außen gedreht. \n- Beuge die Knie, lege die Hüften zurück und gehe in die Hocke, wobei du die Arme zwischen den Beinen auf den Boden fallen lässt.\n- Dann drückst du dich mit den Fersen ab und springst hoch, wobei du die Hände vor der Brust verschränkt hältst. \n- Führe einige Wiederholungen durch.",
  "program_3_ex_3_name": "Liegestütze",
  "program_3_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPushups.mp3?alt=media&token=46aafc2a-66e6-47c1-930a-320aad5148d2',
  "program_3_ex_3_desc":
      "	•	Beginnen Sie in einer normalen Liegestützposition \n•	Ellbogen beugen \n•	Einige Wiederholungen durchführen.​ \n•	Wenn es zu schwierig ist, gehen Sie mit den\nKnien nach hinten und machen Sie die Übung. ",
  "program_3_ex_4_name": "Plank Twists",
  "program_3_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPlank%20Twists.mp3?alt=media&token=1d51db42-410f-4d5b-ae86-f6ce94037e8a',
  "program_3_ex_4_desc":
      " - Beginne in der Plank-Position. \n- Ziehe deinen Bauchnabel so fest wie möglich in Richtung Wirbelsäule. \n- Hebe dann deine Brust und einen Arm in Richtung Decke.\n- Komme zurück in den Plank. Wiederhole die Übung auf der anderen Seite.",
  "program_3_ex_5_name": "Katzen-Hunde-Übung",
  "program_3_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCats%20Dogs%20exercise.mp3?alt=media&token=b738846e-0c8a-41f9-9cc7-535217192b07',
  "program_3_ex_5_desc":
      "	- Stelle dich auf alle Viere und verteile dein Gewicht gleichmäßig. Die Knie sind unter deinen Hüften. Dein Kopf und Nacken bilden eine gerade Linie mit deiner Wirbelsäule. \n- Atme ein und hebe deinen Kopf, bis du nach vorne schaust. \n- Atme aus und ziehe deinen Bauchnabel zu deiner Wirbelsäule, bringe deine Hüfte nach vorne. Ziehe dein Kinn in Richtung Brust. \n- Wiederhole diese Übung für die gewünschte Anzahl an Wiederholungen.",
  "program_4": "Gesunder Nacken",
  "program_4_ex_1_name": "Seitenneigung",
  "program_4_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Tilt.mp3?alt=media&token=fe2671d0-c001-4ccd-8a09-8ff380a75355',
  "program_4_ex_1_desc":
      "•	Halten Sie den Kopf gerade. \n•	Legen Sie die rechte Hand auf das linke Ohr und beugen\nSie den Kopf sanft zur rechten Schulter, hören Sie auf, wenn\nSie sich unwohl fühlen.. \n•	Hände wechseln. ",
  "program_4_ex_2_name": "Vorwärts- und Rückwärtsneigung",
  "program_4_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FForward%20and%20Backward%20Tilt.mp3?alt=media&token=346ffde3-4cd3-460c-928e-9f9ab177512f',
  "program_4_ex_2_desc":
      "- Beginne mit geradem Kopf und Rücken. \n- Senke dein Kinn in Richtung Brust und gehe zurück in die Ausgangsposition. \n- Neige dein Kinn nach oben zur Decke und bringe die Schädelbasis zum Rücken. \n- Wiederhole den Satz mehrere Male.",
  "program_4_ex_3_name": "Seitliche Drehung",
  "program_4_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Rotation.mp3?alt=media&token=da9612fe-6559-47ce-83a1-a52a037ce63f',
  "program_4_ex_3_desc":
      "- Halte deinen Kopf genau über den Schultern und deinen Rücken gerade. \n- Drehe deinen Kopf langsam nach rechts und links, bis du eine Dehnung im Nacken und in den Schultern spürst.",
  "program_4_ex_4_name": "Kopfdrehung",
  "program_4_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHead%20rotation.mp3?alt=media&token=c5817357-2218-400a-bde1-3d8509c1dbb3',
  "program_4_ex_4_desc":
      "•	Sitzen oder stehen Sie mit geradem Kopf und Rücken. \n•	Drehen Sie Ihren Kopf 3 Mal im und gegen den Uhrzeigersinn.",
  "program_4_ex_5_name": "Schultern drehen",
  "program_4_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FShoulders%20rotation.mp3?alt=media&token=ad9f4128-bbe2-42b1-be88-4f9a3a75310e',
  "program_4_ex_5_desc":
      "•	Stellen Sie die Beine schulterbreit auf, halten Sie die Arme entspannt. \n•	Führen Sie die Drehung beider Schultern im und gegen den Uhrzeigersinn sanft durch.",
  "program_4_ex_6_name": "Kuhgesichtspose",
  "program_4_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCow%20Face%20Pose.mp3?alt=media&token=1654d6bc-dba2-4063-a674-9bd4519eb110',
  "program_4_ex_6_desc":
      "•	Stehen Sie gerade, halten Sie Ihre Schultern entspannt. \n•	Verschränken Sie die Hände hinter dem Rücken, so dass ein\nArm nach oben und der andere nach unten zeigt. Spüren Sie die Dehnung. \n•	Hände wechseln und wiederholen. ",
  "exercise_1_title": "Dehnen",
  "exercise_1_text":
      "Beginne mit der Dehnung. \n1. Stelle dich gerade hin, wobei deine Füße weiter als schulterbreit geöffnet sind.\n2. Im Stehen faltest du deine Hände gerade nach oben, die Handflächen zeigen zur Decke.\n3. Dehne dich langsam nach oben und spüre, wie sich dein Körper dehnt.\n4. Halte deinen Kopf und deinen Rücken gerade, beuge dich nicht.\n5. Halte die Bewegung 10 bis 15 Sekunden lang und wiederhole sie drei- bis viermal.",
  "exercise_2_title": "Auf der Stelle marschieren",
  "exercise_2_text":
      "1. Die menschlichen Füße haben viele sensible Punkte, die für die Arbeit der Organe verantwortlich sind. \n\n2. Stelle dich mit den Füßen schulterbreit auseinander und halte die Wirbelsäule gerade, wobei die Hüfte nach vorne zeigt. Bringe dein Knie nach oben, so dass dein Oberschenkel parallel zum Boden ist, setze es dann ab und bringe das andere Bein abwechselnd nach oben.\n\n3. Wiederhole die Übung bis zu fünfzig Sekunden lang.",
  "exercise_3_title": "Fersen- und Zehenspitzenheben",
  "exercise_3_text":
      "1. Stelle dich gerade hin.\n\n2. Stelle deine Füße in einem Abstand von 15 cm zueinander auf.\n\n3. Atme ein und rolle die Fersen zu den Zehen, atme aus und rolle sanft zu den Fersen zurück4. Wiederhole dies 20 bis 25 Mal.",
  "exercise_4_title": "Drehungen",
  "exercise_4_text":
      "1. Die beste Art, sich aufzuwärmen, sind Rotationsübungen.\n\n2. Beginne mit deinem Kopf, dann zu den Handgelenken, Ellbogen, Schultern, Füßen, Knöcheln und Knien.\n\n3. Wiederhole das für jeden Teil deines Körpers mindestens 10 Mal auf jeder Seite.",
  "exercise_5_title": "Abwechselnde Beugen und Kniebeugen",
  "exercise_5_text":
      "Eine einfache, aber effektive Übung hilft, viele wichtige Muskeln zu trainieren.\n\n1. Stelle dich gerade hin, mit den Füßen breiter als schulterbreit, und stütze dich mit den Händen an der Taille ab.\n\n2. Beuge dich sanft nach unten, halte deinen Rücken flach und mache eine Kniebeuge.3. Achte auf deine Haltung, um Verletzungen der Knie zu vermeiden.\n\n4. Mache 10-20 Versuche.",
  "exercise_6_title": "Stehende Seitenbeuge",
  "exercise_6_text":
      "1. Stelle dich mit deinen Füßen etwas weiter als hüftbreit auseinander.\n\n2. Hebe deine rechte Hand.\n\n3. Senke deinen rechten Arm auf der rechten Seite deines Körpers ab und atme aus, während du den linken Arm über den Kopf streckst und den Körper leicht nach rechts beugst.\n\n4. Atme ein, um die Arme über dem Kopf wieder in die Mitte zu bringen und atme aus, während du die Übung auf der linken Seite wiederholst.\n\n5. Wiederhole die Übung mindestens 15 Mal auf jeder Seite.",
  "exercise_7_title": "Fahrrad-Crunch",
  "exercise_7_text":
      "1. Lege dich mit dem Rücken auf den Boden.\n\n2. Deine Füße sollten auf dem Boden stehen und deine Hände sind hinter deinem Kopf.\n\n3. Ziehe mit den Händen, die deinen Kopf halten, deine Schulterblätter nach hinten und hebe deine Knie langsam in einen 90-Grad-Winkel, wobei du deine Füße vom Boden abhebst.\n\n4. Drehe deinen Oberkörper so, dass du deinen Ellenbogen am gegenüberliegenden Knie berührst, wenn es nach oben kommt. 5. Ziele auf 15 Wiederholungen für jedes Bein.",
  "exercise_8_title": "Katze und Hund",
  "exercise_8_text":
      "Diese Übung verbessert die Beugung und Streckung der Wirbelsäule. \n\n1. Lege deine Hände und Knie auf den Boden.\n\n2. Beuge in einer fließenden Bewegung den Rücken, ziehe den Bauch ein und bringe die Hüfte nach vorne.\n\n3. Schaue jetzt nach oben und nicht in deine Beine oder auf den Boden.\n\n4. Wiederhole die Übung mindestens 15 Mal zu jeder Seite.",
  "exercise_9_title": "Liegestütz",
  "exercise_9_text":
      "1. Es gibt Zehen-Liegestütze und Knie-Liegestütze. Die zweite gilt als leichter.\n\n2. Halte deinen Körper in einer geraden Linie und deine Ellbogen nahe am Körper, beuge und strecke deine Arme, um einen Liegestütz zu machen.\n\n3. Wenn die erste Option schwierig ist, beuge dein Knie und mache dasselbe wie bei der ersten Übung.\n\n4. Mache 15 Liegestütze",
  "exercise_10_title": "Handstreckung",
  "exercise_10_text":
      "1. Strecke deine Arme aus, wobei deine Handflächen nach oben zur Decke zeigen.\n\n2. Atme aus, während du deine Arme zur Decke streckst.\n\n3. Atme ein, während du dich auf die Ferse stellst und entspannst.\n\n4. Wiederhole das bis zu 5 Mal, wobei du jedes Mal deine Hände für 10 Sekunden ausstreckst.",
  "fitness": "FITNESS",
  "fitness_title":
      "Bereite dich auf Übungen vor,\ndie deine körperliche Gesundheit wiederherstellen",
  "good_morning": "Guten Morgen",
  "good_afternoon": "Guten Nachmittag",
  "good_evening": "Guten Abend",
  "good_night": "Gute Nacht",
  "meditation": "MEDITATION",
  "al": "Bewerbung",
  "meditation_title":
      "Setze dich in eine bequeme Position \nund konzentriere dich auf deinen Atem.",
  "meditation_select": "Wähle eine Meditation",
  "meditation_menu_1": "Stille",
  "meditation_menu_2": "Nur Musik",
  "meditation_menu_3": "Geführte Meditation",
  "note": "HINWEIS",
  "fitness_program": "Vorgefertigtes Programm",
  "fitness_my_program": "Mein Programm erstellen",
  "visualization": "VISUALISIERUNG",
  "visualization_title":
      "Schließe deine Augen, stelle dir deinen Wunsch vor, berühre ihn, fühle ihn, stelle dir den Weg dorthin Schritt für Schritt vor",
  "visualization_hint": "Schreibe deine Visualisierung, beschreibe sie kurz",
  "diary": "TAGEBUCH",
  "voice_record": "Eine Sprachaufzeichnung",
  "written_record": "Eine schriftliche Aufzeichnung",
  "affirmation": "BESTÄRKUNG",
  "affirmation_title":
      "Sprich deutlich, laut und mit voller Überzeugung und Konzentration aus",
  "your_name": "Dein Name",
  "google": "Anmeldung mit Google",
  "apple": "Mit Apple anmelden",
  "restart": "Neu starten",
  "menu": "Menü",
  "day": "Tag",
  "min": "min",
  "sec": "sec",
  "pull_program":
      "Um dein Programm einzurichten, ziehe die Übungen von oben herunter",
  "add_exercises": "Übungen \nhinzufügen",
  "success": "Erfolg!",
  "vip_restored": "Abonnements wiederhergestellt",
  "pages": "Wie viele Seiten ?",
  "continue": "Weiter",
  "change_tarif": "Tarif ändern",
  "reminders": "Erinnerungen",
  "add_first_reminder": "Füge deine erste Erinnerung hinzu",
  "select_week_day": "Wöchentliche Tage auswählen",
  "set_reminders": "Eine Erinnerung einstellen",
  "stop": "Stoppen",
  "push_success": "Erfolgreich durchgeführt!",
  "action_completed": "Aktion abgeschlossen!",
  "timer_started": "Timer\ngestartet",
  "appreciate":
      "Wir schätzen deine Gemütlichkeit und deinen Komfort und haben deshalb die Anwendung kostenpflichtig gemacht. Damit du nicht durch Werbung abgelenkt werden kannst.",
  "subscribe_futures":
      "Subscription will provide the opportunity to perform exercises such as: Fitness, Tagebuch, Lesen und Visualisierung. Es erneuert sich jeden Monat automatisch, aber du kannst es jederzeit kündigen.",
  "price": "Preis",
  "tarif_month_title": "@days Tage kostenlos",
  "tarif_month_desc": "dann - @price pro Monat",
  "tarif_annual_title": "@price pro Jahr",
  "tarif_annual_desc": "@price pro Monat",
  "well_done": "Gut gemacht!",
  "well_done_desc":
      "Du hast einen tollen Start in den Morgen, bedanke dich und verbringe diesen Tag mit Nutzen.",
  "buy_month": "Abonnement bezahlen",
  "buy_free": "TESTE DEN VOLLEN KOMPLEX",
  "days_free": "@days Tage kostenlos",
  "buy_days": "Teste @days Tage kostenlos",
  "sure": "Bist du dir sicher ?",
  "sure_delete": "Bist du sicher, dass du die Übung löschen willst?",
  "cancel": "Abbrechen",
  "skip": "Überspringen",
  "minutes": "Minuten",
  "choose_sequence": "Reihenfolge\nwählen",
  "choose": "Auswählen",
  "done": "Fertig",
  "choose_title":
      "Durch Ziehen und Ablegen kannst du die Reihenfolge der Übungen ändern und die Zeit für sie festlegen.\n0 min - Übung überspringen.",
  "exercises_note": "Übungen",
  "visualizations_note": "Visualisierung",
  "seconds": "Sekunden",
  "affirmation_small": " Bestärkungen",
  "affirmation_smal": "Bestärkungen",
  "meditation_small": "Meditation",
  "fitness_small": "Fitness",
  "diary_small": "Tagebuch",
  "menu_diary_small": "Tagebuch",
  "Save the Affirmation": "Speichern Sie die Bestärkungen",
  "or": "or",
  "Affirmation Settings": "Bestärkungen Settings",
  "menu_diary_desc": "Schreibe wichtige Gedanken im Tagebuch auf",
  "reading_small": "Lesen",
  "visualization_small": "Visualisierung",
  "fitness_desc": "Trainiere dich mit Fitness",
  "visualization_desc": "Visualisiere deinen Erfolg",
  "reading_desc": "Lass dich am Morgen von Büchern inspirieren",
  "duration": "Dauer des",
  "complex": "komplex: ",
  "magic_morning": "“Wunderbarer Morgen”",
  "write_affirmation": "Schreibe deine\nBestärkung",
  "affirmation_hint": "Schreiben Sie Ihre Affirmation...",
  "book_name": "Schreibe den Namen\ndes Buches",
  "input_cat_name": "Gib den Namen der Kategorie ein",
  "input_desc": "Gib eine Beschreibung ein",
  "player_voice": "Stimme",
  "female": "Weiblich",
  "male": "Männlich",
  "complexs": "complex",
  "language": "Sprache",
  "Add a reminder": "Eine Erinnerung hinzufügen",
  "Are you sure you want to leave the complex":
      "Sind Sie sicher, dass Sie den Komplex verlassen wollen?",
  "x_minutes": "@x Minuten",
  "Monday": "Montag",
  "Tuesday": "Dienstag",
  "Wednesday": "Mittwoch",
  "Thursday": "Donnerstag",
  "Friday": "Freitag",
  "Saturday": "Samstag",
  "Sunday": "Sonntag",
  "leave": "Verlassen Sie",
  "January": "Januar",
  "February": "Februar",
  "March": "März",
  "April": "April",
  "Mayi": "Mai",
  "June": "Juni",
  "July": "Juli",
  "August": "August",
  "September": "September",
  "October": "Oktober",
  "November": "November",
  "December": "Dezember",
  "Are you sure you want to delete a note?":
      "Sind Sie sicher, dass Sie eine Notiz\nlöschen wollen?",
  "How much time are you going to read?":
      "Wie viel Zeit werden Sie für das Lesen?",
  "Delete a note": "Eine Notiz löschen",
  "add_exercise": "Übung hinzufügen",
  "Organize your morning routine with ease using the complex program":
      "Organisieren Sie Ihre morgendliche\nRoutinemit Hilfe des komplexen\nProgramms ganz einfach.",
  "name": "Name",
  "komplex": "Komplex - ",
  "Customize the sequence and duration of your rituals in the":
      "Passen Sie die Reihenfolge und Dauer Ihrer Rituale in der",
  "Settings section": " Abschnitt Einstellungen",
  "is a consistent set of your morning daily rituals. ":
      "ist ein konsistenter\nSatz Ihrer täglichen \nMorgenrituale. ",
  "please_input_name": "Bitte gib deinen Namen ein",
  "delete_exercise": "Übung löschen",
  "delete_hint": "Klammern und halten\nzum Löschen",
  "your_exercise": "Deine Übung",
  "enter_your_exercise": "Gib deine Übung ein",
  "add_permission": "Erlaubnis zur Audioaufzeichnung erteilen",
  "yes": "Ja",
  "For instance": "Zum Beispiel:",
  "1) Meditation - 5 minutes2) Fitness & Yoga - 15 minutes 3) Reading - 20 minutes":
      "1) Meditation - 5 minutes\n2) Fitness & Yoga - 15 minutes \n3) Reading - 20 minutes",
  "no": "Nein",
  "other": "Sonstige",
  "save_diary": "Notiz speichern",
  "Start reading": "Lesen beginnen",
  "Start affirmation": "Bestärkungen starten",
  "mornings": "Morgen ",
  "enter_your_name": "Gib deinen Namen ein",
  "remove_progress": "Fortschritt entfernen",
  "sure_delete_progress":
      "Bist du sicher, dass du den gesamten Bewerbungsfortschritt löschen möchtest ?",
  "and": " und ",
  "agreement_start":
      "Indem du auf “Weiter”, bestätigst du, dass du Folgendes akzeptiertst",
  "agreement_title": "Nutzungsbedingungen",
  "privacy_title": "Datenschutz",
  "paragraph1": "Schreibe wichtige Gedanken in Notizen",
  "paragraph2": "Trainiere dich mit Fitness",
  "paragraph3": "Lass dich am Morgen von Büchern inspirieren",
  "paragraph4": "Visualisiere deinen Erfolg",
  "try_vip_desc":
      "Probiere es ein paar Tage lang kostenlos aus und dann wird der Preis @price pro Monat sein. \n\nDu kannst dein Abonnement jederzeit kündigen",
  "vip_price_card": "1 Monat",
  "vip_def_month_price": "0.99 \$",
  "for_confidence": "Für Selbstvertrauen",
  "for_health": "Für die Gesundheit",
  "for_love": "Für die Liebe (Weiblich)",
  "for_success": "Für den Erfolg",
  "for_career": "Für die Karriere",
  "for_wealth": "Für Reichtum",
  "confidence_text_1":
      "Herausforderungen sind Gelegenheiten, zu wachsen und sich zu verbessern",
  "confidence_text_2": "Ich glaube an meine Fähigkeiten",
  "confidence_text_3":
      "Es gibt keine Hindernisse, die ich nicht überwinden kann",
  "confidence_text_4":
      "Ich bin es wert, mein Leben zu leben und zu bekommen, was ich will",
  "confidence_text_5":
      "Ich erlaube mir, meinen eigenen Weg zu wählen und meine Träume zu verwirklichen",
  "confidence_text_6": "Ich liebe, wer ich bin, innerlich und äußerlich",
  "health_text_1":
      "Mein Körper weiß, wie er sich selbst heilen kann. Ich erlaube der Intelligenz meines Körpers, meine Gesundheit voranzutreiben",
  "health_text_2":
      "Ich glaube an meine Intuition. Ich höre immer auf meine innere Stimme",
  "health_text_3":
      "Ich schlafe leicht ein. Mein Körper, mein Geist und meine Seele haben sich ihre Ruhe verdient",
  "health_text_4":
      "Ich bin im Einklang mit meinem inneren Teil, der die Geheimnisse der Heilung kennt",
  "health_text_5": "Ich werde jeden Tag gesünder und stärker",
  "health_text_6": "Ich habe viel Energie und Lebenskraft",
  "health_text_7":
      "Ich habe die Kontrolle über die geistige Atmosphäre, die ich schaffe. Gedanken können verändert werden und die positiven Gedanken, die ich wähle, helfen mir zu heilen",
  "health_text_8": "Ich bin gesund, glücklich und strahlend",
  "health_text_9": "Ich bin es wert, gesund zu sein",
  "health_text_10": "Ich strahle gute Gesundheit aus",
  "love_text_1":
      "Ich schenke mein Herz und bin bereit, das Herz eines anderen zu empfangen",
  "love_text_2": "Ich fühle, dass ich geliebt werde",
  "love_text_3": "Ich verdiene Liebe und Zuneigung",
  "love_text_4": "Ich bin furchtbar charismatisch",
  "love_text_5":
      "Ich gebe meiner inneren Göttin die Erlaubnis, ihre Magie zu entfalten",
  "love_text_6": "Ich genieße es, eine Frau zu sein",
  "love_text_7": "Ich bin selbstbewusst in meiner Sexualität",
  "love_text_8":
      "Ich bin offen für eine gesunde, liebevolle Beziehung, die für mich richtig ist",
  "love_text_9":
      "Ich bin es wert, etwas zu erreichen, Erfolg zu haben und in Fülle zu leben",
  "love_text_10": "Ich bin einer gesunden, liebevollen Beziehung würdigp",
  "love_text_11":
      "Ich bin in einer wunderbaren Beziehung mit jemandem, der mich gut behandelt!",
  "success_text_1":
      "Ich bin aufgeschlossen und immer bereit, neue Wege zum Erfolg zu gehen",
  "success_text_2":
      "Ich habe die Kraft, mir den Erfolg und Wohlstand zu schaffen, den ich mir wünsche",
  "success_text_3": "Ich bin organisiert und kann mir meine Zeit gut einteilen",
  "success_text_4":
      "Ich fliege hoch hinaus und erfülle immer meine Erwartungen",
  "success_text_5":
      "Ich vertraue auf meine Intuition und treffe immer weise Entscheidungen",
  "success_text_6":
      "Ich ziehe nach und nach die benötigten Umstände zur richtigen Zeit an",
  "success_text_7":
      "Jeden Tag bin ich voller neuer Ideen, die mich motivieren und beflügeln",
  "success_text_8":
      "Ich habe unbegrenzte Macht, alles zu erreichen, was ich will",
  "success_text_9": "Ich treffe kluge Entscheidungen mit Freude",
  "success_text_10":
      "Das Universum will mir helfen und gibt mir alles, was ich brauche",
  "success_text_11": "Ich habe den Mut, alle Preise des Lebens zu nutzen",
  "career_text_1": "Ich bin motiviert, zielorientiert und selbstbestimmt",
  "career_text_2": "Ich erreiche immer meine beruflichen Ziele",
  "career_text_3": "Erfolg im Beruf ist leicht",
  "career_text_4": "Ich werde respektiert und gut behandelt",
  "career_text_5":
      "Genau in diesem Moment wird mein Lebenslauf von den richtigen Leuten gesehen",
  "career_text_6":
      "Ich verdiene einen Job, der mich erfüllt, und jetzt bin ich bereit, ihn zu finden!",
  "career_text_7":
      "Wenn ich meine Karriere mit meinen wahren Talenten in Einklang bringe, fließen das Geld und das Glück zu mir!",
  "career_text_8":
      "Ich arbeite hart! Ich arbeite klug! Ich verdiene die Anerkennung, die ich verdiene!",
  "career_text_9":
      "Heute und jeden Tag nutze ich meine Talente auf befriedigende Weise!",
  "career_text_10": "Ich gestalte meine Karriere nach meinen Zielen!",
  "career_text_11": "Ich bin finanziell abgesichert und tue, was ich will",
  "wealth_text_1": "Ich ziehe auf natürliche Weise das Glück an",
  "wealth_text_2": "Geld ist mein Freund",
  "wealth_text_3": "Ich kann leicht Geld ausgeben und bekommen!",
  "wealth_text_4": "Ich bin ein Geldmagnet! Geld fließt frei zu mir",
  "wealth_text_5":
      "Ich habe eine positive Beziehung zu Geld und weiß, wie ich es weise ausgeben kann",
  "wealth_text_6":
      "Ich sehe die Möglichkeiten, Geld anzuziehen! Ich nutze die besten Gelegenheiten!",
  "wealth_text_7": "Ich bin mit der universellen Versorgung mit Geld verbunden",
  "wealth_text_8": "Das Universum überschüttet mich mit Geschenken",
  "wealth_text_9": "Jede gute Tat kommt vervielfacht zu mir zurück",
  "wealth_text_10": "Ich ziehe immer viele Ressourcen und Ideen an",
  "start_program": "Programm starten",
  "program_settings": "Einstellungen programmieren",
  "restore_default": "Standardeinstellungen\nwiederherstellen",
  "create_yours": "Erstelle\ndein",
  "restore": "Abonnement wiederherstellen",
  "delete": "Löschen",
  "edit": "Bearbeiten",
  "cancellation": "Abbrechen",
  "exercises": "Übungen",
  "add_yours": "Deine erstellen",
  "save": "Speichern",
  "delete_program_alert":
      "Bist du sicher, dass du ein Programm löschen willst?",
  "initial_exercises_empty":
      "Es wurden bereits Standardübungen hinzugefügt Versuche, deine eigene Übung zu erstellen",
  "restore_default_dialog_title":
      " Bist du sicher, dass du die Standardübungen wiederherstellen willst?\nEigene Programme/Übungen werden gelöscht",
  "name_not_be_empty": "Ein Name darf nicht leer sein",
  "type_exercise_name": "Gib einen Übungsnamen ein",
  "type_program_name": "Gib einen Programmnamen ein",
  "type_exercise_description": "TGib eine Übungsbeschreibung ein",
  "hold_to_move_exercise": "Gedrückt halten, um eine Übung zu verschieben",
  "type_name": "Gib einen Namen ein",
  "tutorial_text": "Wie einfach ist es, morgens aufzustehen?",
  "rate_app_title": "App bewerten",
  "rate_app_description": "Deine Bewertung wird uns helfen, besser zu werden",
  "action_rate": " Bewerten",
  "action_remind": "Erinnere mich später",
  "rate_subject": "App-Bewertung",
  "my_progress": "MEIN FORTSCHRITT",
  "Try PREMIUM": "PREMIUM ausprobieren",
  "3 days free": "3 Tage frei",
  "Finish reading": "Lesen beenden",
  "exercise_complete": "Übung abgeschlossen",
  "affirmation_timer": "Bestärkungen",
  "audio_loading": "Audio wird geladen...",
  "success_target": "Erfolg",
  "family_target": "Familie",
  "nature_target": "Natur",
  "rest_target": "Ruhe",
  "sport_target": "Sport",
  "target_selection": "Ziel auswählen",
  "remove_created_target": "Erstelltes Ziel entfernen?",
  "impression_selection": "Eindruck auswählen",
  "remove_image": "Bild entfernen?",
  "target_title": "Titel",
  "target_short_desc":
      "Beschreibe in dem Feld kurz (in einem Satz), was du visualisieren willst",
  "music_menu_music": "Musik",
  "music_menu_sounds": "Klänge",
  "music_menu_meditations": "Meditationen",
  "music_menu_favorite": "Favorit",
  "purchase_page_title": "Entdecke den Morgen auf eine neue Art",
  "purchase_page_desc": "@days Tage kostenlos",
  "go_start_record": "Klicken, um die Aufnahme zu starten",
  "go_stop_record": "Aufnahme läuft, zum Stoppen anklicken",
  "empty_favorite_list": "Du hast keine gespeicherte Musik",
  "purchase_bonuses_image": "assets/images/purchase/bonuses_en.png",
  "faq_menu_title": "Häufig gestellte Fragen",
  "faq_cat_support": "Support",
  "faq_cat_why": "Wofür ist das?\n",
  "faq_cat_tarifs": "Fragen zum Abonnement",
  "faq_tarifs_title_1": "Was bietet das Abonnement?",
  "faq_tarifs_desc_1":
      "<p>-Entfernt Werbung <br>- Zugang zu den Bereichen Fitness, Tagebuch, Lesen, Visualisierungen <br>- Zugang zu zukünftigen neuen Komplexen.</p>",
  "faq_tarifs_title_2": "Warum ist die App nicht kostenlos?",
  "faq_tarifs_desc_2":
      "<p>- kostenlose Waren werden nicht geschätzt, wenn du nicht in Werkzeuge zur Selbstentwicklung investierst, wirst du sie nicht schätzen<br>- alles Geld, das wir von den Abonnenten erhalten, verwenden wir, um die Anwendung zu verbessern</p>",
  "faq_tarifs_title_3": "Wie kann man einen Tarif ändern?",
  "faq_tarifs_desc_3":
      "<p>1. Gehe zum <a href='screen tarifs'>'Tarifplan'</a>-Reiter (du kannst klicken) <br>2. Wähle den gewünschten Tarif aus <br>3. Klicke auf 'Tarif ändern' <br>4. Im nächsten Monat wird der Tarif geändert</p>",
  "faq_tarifs_title_4": "Wie kann ich ein Abonnement wiederherstellen?",
  "faq_tarifs_desc_4":
      "<p>Die Wiederherstellung funktioniert nur, wenn du ein aktives Abonnement hast. Du kannst auf die Schaltfläche \Abonnement wiederherstellen\" klicken oder es manuell tun <br>1. Gehe auf den <a href='screen tarifs'>'Tarifplan'</a>-Reiter (du kannst klicken) <br>2. Klicke unten auf die Wiederherstellung</p>'",
  "faq_tarifs_title_5": "Wie kündige ich ein Abonnement?",
  "faq_tarifs_desc_5":
      "<p>Du kannst es manuell tun oder auf die Schaltfläche <a href='screen:unsubscribe'>'Abmelden klicken'</a></p> .",
  "faq_tarifs_title_6": "Kontakt zum Support",
  "faq_about_title_1": "Wozu sind diese Übungen gut?",
  "faq_about_desc_1":
      "<p>Meditation - hilft, den Geist langsam aufzuwecken und ruhig zu halten <br>Bestärkungen - laden den Geist mit positiven Emotionen auf <br>Visualisierungen - erlauben dir, den gewünschten Erfolg genau darzustellen <br>Fitness - verleiht deinem Körper Energie<br>Lesen - Bildung am Morgen! (vor allem, wenn am Abend nicht genug Zeit ist) <br>Tagebuch - erinnere dich daran, was du getan und gelernt hast, schreibe die wichtigsten Gedanken auf <br>Es ist besser, sich eine Stunde am Tag Zeit zu nehmen und sich auf den ganzen Komplex einzulassen, aber zumindest ein paar Übungen durchzuführen, wird schon Wirkung zeigen.</p>",
  "faq_about_title_2": "Wie wird es angewendet?",
  "faq_about_desc_2":
      "<p>Beginne mit den Einstellungen<br>Dort kannst du die <br>Zeit jeder Übung einstellen<br>-Die Reihenfolge des Komplexes <br>- Die Bestärkung als Standard <br>- Das Buch, das du liest <br>Die Einstellungen können jederzeit geändert werden. <br>Nachdem du die Einstellungen vorgenommen hast, kannst du auf die Schaltfläche <br>“Start” klicken und alles wird entsprechend der gewählten Einstellungen geschehen</p>”",
  "faq_about_title_3": "Warum sollte ich das benutzen?",
  "faq_about_desc_3":
      "<p>Das Üben hilft dir, dich auf den Tag einzustimmen, lädt dich mit Fröhlichkeit auf und hilft, Stress loszuwerden<br>Viele Topmanager und erfolgreiche Menschen entscheiden sich dafür, früher aufzuwachen, um bessere Ergebnisse zu erzielen. Es ist aber auch nützlich, wenn du einfach nur deine Energie aufladen oder deine mentale Einstellung verbessern willst.</p>>",
  "faq_about_title_4": "Wann sehe ich das Ergebnis?",
  "faq_about_desc_4":
      "<p>Nach 10 Tagen wird es möglich sein, eine Gewohnheit zu entwickeln<br>Nach einem Monat der Anwendung wirst du spüren, dass es viel leichter geworden ist, aufzuwachen, und dass der Stress spürbar weniger geworden ist.</p>",
  "faq_about_title_5": "Wie richte ich Fitness ein?",
  "faq_about_desc_5":
      "<p>1. Klicken Sie auf <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F02-min%20(1).png?alt=media&token=5f53f785-9dd5-4a46-957e-0f8a7dca7f62' width='25' /> in Einstellungen <br>2. Wählen Sie das Programm, das Sie bearbeiten möchten <br>3. Bearbeiten anklicken <br>Es gibt ein Problem? <a href='screen:support'>Unterstützung</a></p>",
  "faq_about_title_6": "Wie stelle ich Visualisierungen ein?",
  "faq_about_desc_6":
      "<p>1. Um ein Ziel hinzuzufügen, klicken Sie auf die Schaltfläche <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F01-min.png?alt=media&token=17783548-ef94-40ed-87ed-db6a3979e0ac' width='25' /> in der Zielauswahl <br>2. Wählen Sie dann das Bild aus den auf Ihrem Handy gespeicherten Bildern aus. <br>3. Wait while the images are loaded <br>4. Sie können vorgefertigte Ziele und Bilder verwenden oder Ihre eigenen Bilder zu den Zielen hinzufügen, indem Sie dieselben Anweisungen befolgen. <br>Gibt es ein Problem? <a href='screen:support'>Unterstützung</a></p>",
  "welcome_to_sleep": "Willkommen beim Schlaf",
  "meditation_subtitle":
      "Höre dir eine unserer Meditationen zum Stressabbau an",
  "music_for_sleep_subtitle": "Einschlafen mit deiner Lieblingsmusik",
  "music_for_sleep_title": "Schlafgeräusche",
  "reading_at_night_title": "Lesen in der Nacht",
  "reading_at_night_subtitle":
      "Wenn du es vorziehst, vor dem Schlafengehen zu lesen",
  "music_instrument_title": "Musikinstrumente",
  "instrument_1": "Harfe",
  "instrument_2": "Glucophon",
  "instrument_3": "Mundharmonika",
  "instrument_4": "Hölzerne Löffel",
  "instrument_5": "Wiegenlied",
  "Do you have trouble": "Fällt es dir schwer, dich zu\n",
  "What do you want to ": "Was willst du mit\n",
  "concentrating?": "konzentrieren?",
  "to get out of My Morning?": "My Morning erreichen?",
  "instrument_6": "Klavier",
  "instrument_7": "Geige",
  "instrument_8": "Die Flöte",
  "music_instrument_places": "Orte",
  "onb3p1": "Continue",
  "place_1": "Im Kaffeehaus",
  "place_2": "Dorf",
  "place_3": "Zug",
  "place_4": "Der Strom der Autos",
  "place_5": "Flugzeug",
  "place_6": "Baustelle",
  "place_7": "Menschenmenge",
  "music_instrument_other": "Andere",
  "other_1": "Ventilator",
  "other_2": "Autoscheibenwischer",
  "other_3": "Tastatur",
  "other_4": "Glocken",
  "other_5": "Herz",
  "other_6": "Uhr",
  "music_instrument_sound_of_nature": "Klänge der Natur",
  "nature_1": "Wind im Gras",
  "nature_2": "Wasserfall",
  "nature_3": "Schneesturm und Schnee",
  "nature_4": "Donner",
  "nature_5": "Regen und Regenschirm",
  "nature_6": "Regen und Zelt",
  "nature_7": "Regen in einer Pfütze",
  "nature_8": "Gewitter",
  "nature_9": "Regen",
  "nature_10": "Tropfend",
  "nature_11": "Regenschauer",
  "nature_12": "Feuer",
  "nature_13": "See",
  "nature_14": "Ozean",
  "nature_15": "Unterwasser",
  "nature_16": "Strom",
  "nature_17": "Starker Wind",
  "nature_18": "Knirschender Schnee",
  "nature_19": "Rascheln von Gras",
  "music_instrument_living_creatures": "Lebendige Dinge",
  "creatures_1": "Wal",
  "creatures_2": "Katze schleckt Milch",
  "creatures_3": "Pferd galoppiert",
  "creatures_4": "Das Pferd kommt",
  "creatures_5": "Frosch",
  "creatures_6": "Frösche",
  "creatures_7": "Katzenschnurren",
  "creatures_8": "Vögel",
  "creatures_9": "Vögel 2",
  "creatures_10": "Grillen",
  "creatures_11": "Eule",
  "creatures_12": "Möwe",
  "save_selected": "Ausgewählte speichern",
  "my_night": "Meine Nacht",
  "onb_1_text_1":
      "Hallo!@dIch bin dein Mentor und ich werde deinen Morgen perfekt machen.",
  "onb_1_btn": "Wie wirst du mir helfen?",
  "onb_2_text_1":
      "Meine Aufgabe ist es,@ddas tägliche Chaos unter Kontrolle zu bringen und ein perfektes System zu schaffen, das dein Leben grundlegend verändern wird.",
  "onb_2_btn": "Wie werden wir das machen?",
  "onb_3_text_1":
      "Jeden Morgen@dwirst du mit einer Reihe von Gewohnheiten und Ritualen beginnen. Sie geben dir die nötige Lebendigkeit, Energie und Motivation für den ganzen Tag!",
  "onb_3_btn":
      "Wie wird sich mein Leben dadurch\n                        verändern?",
  "onb_4_btn":
      "Sehr gut! Kannst du mir etwas über\n      die Gewohnheiten erzählen?",
  "onb_5_text_1":
      "Die Macht liegt in den kleinen Schritten!@dJeden Tag wirst du dein Leben Schritt für Schritt, Stück für Stück gestalten. Ich garantiere dir, dass du dich in zwei Monaten nicht wiedererkennen wirst!",
  "onb_6_text_1": "Gewohnheit Nr. 1",
  "onb_6_text_2": "Morgengymnastik",
  "onb_6_text_3":
      "Jeder weiß es, aber keiner tut es!@dAber wenn du sie richtig machst, ist sie viel wirkungsvoller als Kaffee und der effektivste Weg, um sich zu stärken und endlich aufzuwachen!",
  "onb_6_text_4":
      "Mach dich bereit für eine Reihe spezieller Übungen, die dir in 5 Minuten einen Energieschub und Auftrieb für den ganzen Tag geben!",
  "onb_6_btn": "Gewohnheit Nr. 2",
  "onb_7_text_1": "Gewohnheit Nr. 2",
  "onb_7_text_2": "Lesen",
  "onb_7_text_3":
      "Dafür hat man nie Zeit!@dUnd deshalb ist der Morgen die perfekte Zeit, um Bildungsliteratur zu lesen, während alle noch schlafen!",
  "onb_7_text_4":
      "Ich werde dir dabei helfen, dass du ein wenig liest, aber jeden Tag. Denk daran - die Kraft liegt in kleinen Schritten!",
  "onb_7_btn": "Gewohnheit Nr. 3",
  "onb_8_text_1": "Gewohnheit Nr. 3",
  "onb_8_text_2": "Planung",
  "onb_8_text_3":
      "Um einen produktiven Tag zu haben,@dmusst du wissen, was zu tun ist! Dazu schreibst du dir jeden Morgen einen Plan für den Tag.",
  "onb_8_text_4":
      "Du schreibst deine Pläne und Ziele sowie deine Gedanken und Ideen direkt in der App auf oder nimmst sie im Audioformat auf.",
  "onb_8_btn": "Gewohnheit Nr. 4",
  "onb_9_text_1": "Gewohnheit Nr. 4",
  "onb_9_text_2": "Meditationen",
  "onb_9_text_3":
      "Befreie deinen Geist von unnötigen Gedanken.@dMeditation ist eine der brauchbarsten Praktiken. Sie wirkt sofort auf dich und dieser Effekt verstärkt sich jedes Mal.",
  "onb_9_text_4":
      "Die Meditationen sind in die Anwendung eingebettet. Wir haben alles durchdacht - einfach einschalten und üben!",
  "onb_9_btn": "Gewohnheit Nr. 5",
  "onb_10_text_1": "Gewohnheit Nr. 5",
  "onb_10_text_2": "Bestärkungen",
  "onb_10_text_3":
      "Hast du schon lange@dvon etwas geträumt? Die Praxis der Bestärkungen ermöglicht es dir, dein Unterbewusstsein neu zu programmieren und es auf die Erfüllung deiner Ziele und Wünsche einzustellen.",
  "onb_10_text_4":
      "Mit dem eingebetteten Bestärkungssystem kannst du ganz natürlich und effektiv üben.",
  "onb_10_btn": "Was noch?",
  "onb_11_text_1": "Vollständige Statistiken",
  "onb_11_text_2":
      "Detaillierte Statistiken über alle Gewohnheiten, damit du deine Fortschritte verfolgen kannst",
  "onb_11_text_3": "Bist du also bereit, dein Leben zu verändern?",
  "onb_11_btn": "Ich bin bereit! Los geht's!",
  "paywall_title": "MY MORNING\nKOSTENLOS ausprobieren",
  "popular": "Beliebt",
  "profitable": "Lohnend",
  "cancel_subscribe_any_time": "Jederzeit kündbar",
  "text": "Text",
  "your_own_ritual": "Dein eigenes Ritual",
  "support_text_title": "Take the Survey",
  "support_text_body": "And help the development of the application.",
};
