Map<String, String> translations_po = {
  'onb_3_1_title': 'Não deixe para\n       depois!',
  'onb_3_1_subtitle':
      'Cuide de si mesmo e construa hábitos matinais que mudarão a sua vida para sempre',
  'onb_3_2_title_1': 'A que horas você costuma\n',
  'onb_3_2_title_2': 'acordar?',
  'onb_3_3_title_1': 'Você procrastina\n',
  'onb_3_3_title_2': 'muito?',
  'onb_3_3_item_1_name_1': 'Sim, ',
  'onb_3_3_item_1_name_2': 'e eu quero\nmudar isso',
  'onb_3_3_item_2_name_1': 'Não, ',
  'onb_3_3_item_2_name_2': 'eu consigo manter\no foco',
  'onb_3_3_item_3_name_1': "Não ",
  'onb_3_3_item_3_name_2': 'tenho certeza',
  'onb_3_4_title_1': 'Você tem problemas para se \n',
  'onb_3_4_title_2': 'concentrar?',
  'onb_3_4_item_1_name_1': 'Sim, ',
  'onb_3_4_item_1_name_2': 'eu me distraio\nfacilmente',
  'onb_3_4_item_2_name_1': 'Não, ',
  'onb_3_4_item_2_name_2': "consigo me concentrar\nsem me distrair",
  'onb_3_4_item_3_name_1': "Não ",
  'onb_3_4_item_3_name_2': 'tenho certeza',
  "nexting": "Continuar",
  'onb_3_5_title_1': 'O que você espera ',
  'onb_3_5_title_2': 'ganhar com\no My Morning?',
  'onb_3_5_item_1_name_1': 'Eu quero ',
  'onb_3_5_item_1_name_2': 'construir bons\nhábitos',
  'onb_3_5_item_2_name_1': 'Eu quero ',
  'onb_3_5_item_2_name_2': "planejar\nmelhor o meu dia",
  'onb_3_5_item_3_name_1': "Não ",
  'onb_3_5_item_3_name_2': 'tenho certeza',
  "lets go": "Vamos lá!",
  "subscription": "Assinatura",
  "settings_desc": "Configure a sua rotina",
  "start_complex": "Iniciar rotina",
  "set_timer": "Definir temporizador",
  "dont_add_time": "Não alterar o tempo",
  "select": "Selecionar",
  "Continue": "Continuar",
  "How much": "Por quanto ",
  "sleep": "tempo você\n",
  "do you usually get at hight": "costuma dormir à noite?",
  "Morning": "Manhã",
  "hours": " horas",
  "hours or": " horas ",
  "less": "ou menos",
  "more": "ou mais",
  "Evening": "Noite",
  "Unlock all features": "Desbloquear todos\n       os recursos",
  "Build your perfect morning routine":
      "Construa uma rotina matinal perfeita para você",
  "Got it! Do you": "Entendi! Você ",
  "wake up": "sente que\n ",
  "feeling well-rested?": "está descansado ao acordar?",
  "Always": "Sempre",
  "Usually": "Geralmente",
  "Sometimes": "Às vezes",
  "High ": "Alto ",
  "Medium ": "Médio ",
  "meditation is complete": "A meditação está completa",
  "Low ": "Baixo ",
  "- energized troughot the day": "- muita energia durante todo o dia",
  "- i have bursts of energy": "- Eu tenho explosões de energia",
  "- my energy fades troughout the day":
      "- minha energia desaparece ao longo do dia",
  "How satisfied are you with your ": "Qual é o seu nível de satisfa\nção com ",
  "current fitness level?": "o seu\ncondicionamento físico atual?",
  "Completeli ": "Completo ",
  "Somewhat ": "Moderado ",
  "Not at all ": "Nenhum ",
  "- I feel fit and healthy": "- Me sinto em forma e saudável",
  "- I'd like to see some                 improvement":
      "- Gostaria de ver algumas mudanças",
  "- I'd like to see a major change":
      "- Eu gostaria de ter mudanças importantes",
  "Over the past year, what's been ": "Ao longo do ano passado,\nqual foi ",
  'your experience': 'a sua experiência ',
  " building better habits?": "ao\nconstruir hábitos melhores?",
  "I have been ": "Tenho melhorado ",
  "I have built ": "Eu construí ",
  "I have tried t build good habits,": "Tentei construir bons hábitos,\n",
  "I have not tried ": "Eu não tentei",
  "constantly improving my habits": "meus\nhábitos constantemente",
  "some good habits": "alguns\nhábitos bons",
  "but have not kept up with them": "mas não consegui",
  "to build new habits": "construir novos\nhábitos",
  "Rarely": "Raramente",
  "7one": "",
  "7two": "",
  "7tree": "",
  "7four": "",
  "More  ": "Mais  ",
  "energy": "energia",
  "productivity": "produtividade",
  "mindfulness": "atenção plena",
  "Sleep": "sono",
  "We hear you. What single change ":
      "Te entendemos. Se pudesse escol\nher uma, qual das s ",
  "would improve your life right now?":
      "eguintes\nopções melhoraria a sua vida agora?",
  "8tree": "",
  "How often ": "Com que frequência ",
  "do you focus": "você se concentra ",
  "on the past or futue?": "no passado ou no\nfuturo?",
  "Never ": "Nunca ",
  "Some ": "Algumas ",
  "Most ": "Na maior p",
  "All ": "O tempo ",
  "of the time1": "vezes",
  "of the time2": "arte do tempo",
  "of the time3": "todo",
  "How ": "Com que ",
  " are you?": "s\ndistrai?",
  "distractable": "frequência você ",
  "Easily ": "Muito ",
  "Sometimes ": "Às vezes ",
  "Rarely ": "Raramente ",
  "Laser ": "Nunca ",
  "distracted": "frequentemente",
  "lose focus": "Às vezes",
  " focus": " ",
  "You're embarking on this journey ": "Você está embarcando nesta\njornada ",
  "to build more Energy": "para ter mais energia",
  "Fitness": "Aptidão",
  "Visualization": "Visualização",
  "Monthly": "Mensal",
  "Annually": "Anual",
  "/month,\ncancel anytime": "/mês,\ncancelar\na qualquer",
  "/year,\ncancel anytime": "/ano,\ncancelar\na qualquer",
  ", one-\ntime payment": ", paga\nmento único",
  "Lifetime": "Vitalício",
  "Restore": "Restaurar",
  "Terms": "Termos",
  "Privacy": "Privacidade",
  "month, cancel anytime": "/mês,\ncancele a qualquer momento",
  "year, cancel anytime": "/mês,\ncancele a qualquer momento",
  "one-time payment": ", pagamento único",
  "Start 3 days free trial": "Iniciar 3 dias de teste gratuito",
  "Meditationse": "Meditações",
  "your entire morning routine in one app":
      "a sua rotina matinal completa\nem um só aplicativo",
  "Reading": "Leitura",
  "Just ": "Praticar por apenas ",
  "Customize the sequence and duration of your rituals in the Settings section.":
      "Personalize a sequência e duração dos seus rituais na secção Definições.",
  "30 minutes every day for a year ": "30\nminutos diários,durante\num ano, ",
  "will change your life dramatically!": "mudarão a sua\nvida drasticamente!",
  "Ready": "Gostaria\n",
  "to start?": "de começar?",
  "Notes": "Notas",
  "Affirmations": "Afirmações",
  "We’re finalizing your personalized journey...":
      "Estamos quase acabando a\npersonalização da sua jornada...",
  "I live in the present": "- Eu vivo no presente",
  "minutes": "minutos",
  "How much time ": "Quanto tempo ",
  "Understood! Throughout your day, how are your":
      "Entendido! Ao longo do dia,\ncomo ficam seus ",
  "energy levels": "níveis de\nenergia?",
  "energy levels two": "",
  "do you have ": "você tem\n",
  "at the start of your day?": "disponível no\ninício do seu dia?",
  "Change your life with": "Mude a sua vida com\n",
  "morning rituals": "rotinas matinais",
  "Set your own time": "Defina o seu próprio tempo",
  "Statistics": "Estatísticas",
  "Notifications": "Notificações",
  "How much time are you going to read": "Quanto tempo vai ler?",
  "own_time": "Tempo próprio",
  "1_hour": "1 hora",
  "Choose an affirmation": "Escolha uma afirmação",
  "input your name": "Introduza o seu nome",
  "thanks_to_interview": "Agradecemos muito e levaremos isso em consideração!",
  "help_us": "Ajude nos",
  "Complete": "Completo",
  "Add note": "Criar uma nota",
  "Save note": "           Salvar uma nota           ",
  "Recording paused": "Gravação em pausa",
  "Mindful minutes per week": "Minutos atentospor semana",
  "Recording in progress": "Gravação em curso",
  "Write something here..": "Escreva algo aqui...",
  "more_not_show": "Não mostrar novamente",
  "interview_dialog_text":
      "Olá! Você quer testar gratuitamente por 14 dias? Então é só responder a pesquisa para nos ajudar a melhorar este aplicativo!",
  "interview_dialog_text_vip":
      "Olá! Agradecemos por usar a versão completa do aplicativo. Queremos sempre melhorá-lo e essas pesquisas ajudam muito.",
  "question_1":
      "Vamos nos conhecer melhor. Fale mais sobre você: idade, sexo, país (opcional)",
  "question_2": "É difícil para você acordar de manhã?",
  "question_2_subquestion_1": "Se sim, por quê?",
  "question_3": "Você usa aplicativos para melhorar sua saúde mental e física?",
  "question_3_subquestion_1": "Se sim, quais?",
  "question_4": "Você gostou dos nossos recursos gratuitos?",
  "question_5": "Por que você escolheu nosso produto? ",
  "question_6": "O que você estava procurando quando encontrou nosso produto?",
  "question_7": "Encontrou o que estava procurando?",
  "question_8": "Quais benefícios você obtém do nosso aplicativo?",
  "question_9": "Quais funções são necessárias para você?",
  "question_10":
      "O que você adicionaria? O que você removeria? O que você mudaria?",
  "question_11": "Na sua opinião, é uma boa ideia introduzir práticas diárias?",
  "question_11_subquestion_1":
      "Se sim, quais? (respiração, exercícios diurnos)",
  "question_12":
      "Na sua opinião, é uma boa ideia introduzir práticas noturnas?",
  "question_12_subquestion_1":
      "Se sim, quais? (sons para dormir, preparação para dormir)",
  "question_13":
      "Se você gostaria de participar de uma entrevista conosco, pedimos para que deixe o seu e-mail para nos comunicarmos com você posteriormente",
  "interview_2_q_1":
      "Vamos nos conhecer melhor. Fale mais sobre você: idade, sexo, país (opcional)",
  "interview_2_q_2": "O aplicativo não atendeu às suas expectativas? Por que?",
  "interview_2_q_3": "Você gostou dos nossos recursos gratuitos?",
  "interview_2_q_4": "Quais benefícios você obtém do nosso aplicativo?",
  "interview_2_q_5": "Que funções você considera necessárias?",
  "interview_2_q_6":
      "O que você adicionaria? O que você removeria? O que você mudaria?",
  "interview_2_q_7":
      "Na sua opinião, é uma boa ideia introduzir práticas diárias?",
  "interview_2_q_7_sub_1": "Se sim, quais? (respiração, exercícios diurnos)",
  "interview_2_q_8":
      "Na sua opinião, é uma boa ideia introduzir práticas noturnas?",
  "interview_2_q_8_sub_1":
      "Se sim, quais? (sons para dormir, preparação para dormir)",
  "interview_2_q_9":
      "Se você gostaria de participar de uma entrevista conosco, pedimos para que deixe o seu e-mail para nos comunicarmos com você posteriormente",
  "please_fill_all_fields": "Pedimos para que preencha todos os campos",
  "lets_acquainted": "Vamos nos conhecer melhor",
  "welcome_page_title": "Prazer em conhecer!",
  "welcome_page_subtitle":
      "Este aplicativo foi projetado para confortar você. Através de aulas curtas de meditação e outras rotinas, você iniciará as suas manhãs com mais vigor, aliviar o estresse, ter mais foco no seu dia e dormir melhor à noite.",
  "welcome_push_title": "Quando você gostaria de acordar?",
  "welcome_push_subtitle":
      "Escolha a hora e ajudaremos você a não dormir demais",
  "start_input": "Pode começar a escrever...",
  "start": "Iniciar",
  "Starting": "Iniciar",
  "progress_item": "Progresso",
  "settings": "Configurações",
  "pay": "Adquirir assinatura",
  "store_app": "Loja",
  "al": "Aplicar",
  "user_is_pro": "Assinado",
  "tarif_plans": "Valor do plano",
  "tarif_plans_done": "Assinado",
  "upsell_screen": "Compra antecipada",
  "loading_buy": "Carregando",
  "loading_buy_app_bar": "Carregando...",
  "start_fitness_my_program": "Inicie seu programa",
  "awareness_meter": "Medidor de\natenção plena",
  "month": "Mês",
  "year": "Ano",
  "total": "Total",
  "for_week": "Por semana\n",
  "skip_note": "pular",
  "skip": "Pular",
  "pages_note": "páginas",
  "pages_short": "páginas",
  "minutes_per_week": "minutos",
  "monday_short": "seg",
  "have_not_sub": "Você não possui assinatura",
  "no_sound": "Não há sons",
  "tuesday_short": "ter",
  "wednesday_short": "qua",
  "thursday_short": "qui",
  "tutorial_asset": "assets/audios/tutorial_eng.mp3",
  "friday_short": "sex",
  "saturday_short": "sab",
  "sunday_short": "dom",
  "count_of_sessions": "Práticas\nconcluídas",
  "minutes_of_awareness_with_myself": "Minutos de\natenção plena\nconsigo",
  "count_of_completed_sessions": "Rotinas\nconcluídas",
  "my_diary": "Meu diário",
  "my_exercises": "Meus exercícios",
  "my_affirmations": "Minhas frases",
  "my_books": "Meus livros",
  "my_visualization": "Minhas visualizações",
  "choose_ready": "Escolha uma",
  "add_note": "Adicionar nota",
  "PREMIUM activated": "PREMIUM activado",
  "Add your": "Adicione o seu",
  "Start": "Comece a ler",
  "Try PREMIUM Package for free": "Experimente o pacote PREMIUM\ngratuitamente",
  "Choose favorite meditations": "Escolher meditações\n favoritas",
  "Finish meditating": "Acabar a meditação",
  "5 min": "5 minutos",
  "10 min": "10 minutos",
  "min 1": "minutos",
  "2 min": "2 minutos",
  "3 min": "3 minutos",
  "Fitnes": "Fitness",
  "Edit": "Editar",
  "15 min": "15 minutos",
  "Favorites": "Favoritos",
  "Meditations": "Meditações",
  "You haven't added any meditations to your favorites":
      "Ainda não acrescentou\n nenhuma meditação\n aos seus Favoritos",
  'Mon': 'Seg',
  'Tue': 'Ter',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Sex',
  'Sat': 'Sábado',
  'Sun': 'Sol',
  'Jan': 'Jan',
  'Feb': 'Fev',
  'Mar': 'Mar',
  'Apr': 'Abr',
  'May': 'Maio',
  'Jun': 'Jun',
  'Jul': 'Jul',
  'Aug': 'Ago',
  'Sep': 'Set',
  'Oct': 'Out',
  'Nov': 'Nov',
  'Dec': 'Dez',
  "faq": "Perguntas frequentes",
  "reading": "LEITURA",
  "reading_title":
      "Escolha uma posição confortável e prepare-se para ler um livro",
  "next_button": "Próximo",
  "progress": "PROGRESSO",
  "progress_title": "Você não teve uma manhã tão boa assim.",
  "back_button": "Voltar",
  "check internet connection": "cverifique a conexão com a internet",
  "timer": "Temporizador",
  "exercise": "Exercício @id",
  "listen_to": "Escutar",
  "next_exercise": "Próximo exercício",
  "program_1": "Ioga “Saudação ao Sol - Surya Namaskar”",
  "program_1_ex_1_name": "Hasta Uttanasana",
  "program_1_ex_1_desc":
      "•  Fique com a coluna ereta e levante as duas mãos acima da cabeça. Deixe os dois braços na mesma distância dos seus ombros.\n• Levante os braços e dobre o tronco para trás ao mesmo tempo. Inspire profundamente enquanto levanta os braços.• \nVolte para a posição inicial.",
  "program_1_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHasta%20Uttanasana.mp3?alt=media&token=c010bab3-eb1f-4cd6-9199-d12b2836ed26',
  "program_1_ex_2_name": "Uttanasana",
  "program_1_ex_2_desc":
      "- Levante-se de pé e respire fundo\n- Numa exalação, estenda o tronco para baixo.\n- Fique longo ao longo do pescoço sem arredondar as costas.",
  "program_1_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FUttanasana.mp3?alt=media&token=60ed84bd-c90e-4ffa-b5ac-f12990c4b613',
  "program_1_ex_3_name": "Ashwa Sanchalanasana",
  "program_1_ex_3_desc":
      "•	• Faça a posição do cachorro olhando para baixo.\n• Expire e leve o joelho direito em direção ao nariz. Mantenha o joelho \ndireito dobrado em um ângulo de 90 graus• \nLevante os braços em direção ao céu, abaixe o joelho esquerdo e deslize o joelho direito de volta para a posição Mesa ou, alternativamente, coloque o pé direito de volta na posição do Cachorro olhando para baixo.",
  "program_1_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAshwa%20Sanchalanasana.mp3?alt=media&token=adac340e-29b7-4b46-a2b5-4015c65c2a04',
  "program_1_ex_4_name": "Adho Mukha Svanasana",
  "program_1_ex_4_desc":
      "•	• Fique de quatro com as mãos a cerca de 5 cm à frente dos ombros, e mantenha-as afastadas na mesma distância dos seus ombros.\n• Inspire. Expire e entre na posição do cachorro olhando para baixo. Pressione firmemente com a ponta dos dedos e puxe os antebraços em direção à frente da sala. Você pode dobrar os joelhos.\n• Volte para a posição inicial.",
  "program_1_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FAdho%20Mukha%20Svanasana.mp3?alt=media&token=2499d895-ebf7-44cd-8255-1b51d52a33b1',
  "program_1_ex_5_name": "Bhujangasana",
  "program_1_ex_5_desc":
      "1. Deite-se de barriga para baixo.\n2. Coloque as palmas das mãos no chão diretamente embaixo dos ombros\n3. Inspire para levantar o peito do chão. Mantenha as nádegas e pernas esticadas.",
  "program_1_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBhujangasana.mp3?alt=media&token=fe0835bb-cca4-4141-9651-678c0fac3f28',
  "program_1_ex_6_name": "Gomukhasana",
  "program_1_ex_6_desc":
      "Comece em uma posição sentada, com as pernas cruzadas como mostra a imagem\n• Inspire e levante os braços em direção ao teto. Expire e segure ambas as mãos atrás das costas.\n• Volte à posição inicial e alterne as pernas e os braços.",
  "program_1_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FGomukhasana.mp3?alt=media&token=47a01e08-b6b7-4045-8aa9-733bc7a39fc2',
  "program_2": "Bons espíritos",
  "program_2_ex_1_name": "Marcha",
  "program_2_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FWalk-in-Place.mp3?alt=media&token=0210ca41-b307-43bf-8e83-1e360d9b9422',
  "program_2_ex_1_desc":
      "- Levantar perna direita, braços de lado \n- Levantar perna direita, baixar perna direita; levantar perna esquerda, baixar perna esquerda",
  "program_2_ex_2_name": "Curva lateral em pé",
  "program_2_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend.mp3?alt=media&token=51ad278d-44e8-49bc-9b11-99a5b8b074a4',
  "program_2_ex_2_desc":
      "• Fique em pé e alinhe seus pés e pernas com os ombros.\n• Abaixe o braço direito junto ao corpo e expire, enquanto alonga o braço esquerdo sobre a sua cabeça, dobrando o corpo suavemente para a direita. Expire e repita para o lado esquerdo.",
  "program_2_ex_3_name": "Agachamento com rotação corporal",
  "program_2_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20body-rotation.mp3?alt=media&token=418c6afc-3ec0-48b6-a6e8-6a36dc9ed335',
  "program_2_ex_3_desc":
      "• Fique em pé, com os pés afastados na largura dos ombros.\n• Faça um agachamento. \n• Em seguida, gire o corpo e levante o braço direito para cima da cabeça. Transfira o peso para os pés direitos ou esquerdos ao levantar os dedos dos pés. \n• Repita o agachamento e mude o lado.",
  "program_2_ex_4_name": "Equilíbrio",
  "program_2_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBalance.mp3?alt=media&token=2d14b8ed-bcda-4ee2-a56f-959e3203e8c9',
  "program_2_ex_4_desc":
      "• Fique em pé, com os braços ao lado do corpo. Levante a perna direita e dobre-a para trás com a mão direita.\n• Mantenha-se de pé com a perna esquerda, estique a mão esquerda para frente e levante a perna direita com a mão direita para trás.\n• Mantenha a posição por algum tempo e fique de pé normalmente.\n • Repita para a outra perna.",
  "program_2_ex_5_name": "Ponte",
  "program_2_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FBridge.mp3?alt=media&token=efbe555e-42b7-4673-b290-36c5b78ccb38',
  "program_2_ex_5_desc":
      "• Deite-se de costas com as mãos ao lado do corpo, com os joelhos dobrados e os pés apoiados no chão debaixo dos joelhos.\n• Levante os quadris para criar uma linha reta dos joelhos aos ombros. Contraia os músculos do abdômen e das nádegas \n• Faça pelo menos 20 repetições.",
  "program_3": "Mover montanhas",
  "program_3_ex_1_name": "Curva lateral em pé",
  "program_3_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FStanding%20Side%20Bend%20copy.mp3?alt=media&token=23112729-ce26-48d7-9bd6-66f7a86a404e',
  "program_3_ex_1_desc":
      "• Fique em pé e alinhe seus pés e pernas com os ombros.\n• Abaixe o braço direito junto ao corpo e expire, enquanto alonga o braço esquerdo sobre a sua cabeça, dobrando o corpo suavemente para a direita. Expire e repita para o lado esquerdo.",
  "program_3_ex_2_name": "Agachamento com pulos",
  "program_3_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSquats%20with%20Jumps.mp3?alt=media&token=8c827f9b-0cc8-4530-baf7-0e1a306f290f',
  "program_3_ex_2_desc":
      "• Fique em pé, com os calcanhares mais afastados do que a distância dos ombros e com os dedos dos pés ligeiramente virados para fora\n• Dobre os joelhos e abaixe-se para fazer um agachamento, abaixando os braços para tocar no chão entre as pernas.\n• Em seguida, pule através do calcanhar e com as mãos cruzadas no peito.\n • Faça algumas repetições.",
  "program_3_ex_3_name": "Flexões",
  "program_3_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPushups.mp3?alt=media&token=46aafc2a-66e6-47c1-930a-320aad5148d2',
  "program_3_ex_3_desc":
      "	- Comece numa posição de flexão padrão \n- Dobre os cotovelos \n- Faça algumas repetições \n- Se for demasiado difícil, volte para trás e faça o exercício. ",
  "program_3_ex_4_name": "Prancha",
  "program_3_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FPlank%20Twists.mp3?alt=media&token=1d51db42-410f-4d5b-ae86-f6ce94037e8a',
  "program_3_ex_4_desc":
      "• Comece na posição da prancha.\n • Puxe o abdômen para dentro o máximo que conseguir, de maneira firme e o mais próximo da coluna.\n • Em seguida, levante o peito e um braço em direção ao teto.\n• Retorne à posição da prancha. Repita para o outro lado",
  "program_3_ex_5_name": "Postura do gato",
  "program_3_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCats%20Dogs%20exercise.mp3?alt=media&token=b738846e-0c8a-41f9-9cc7-535217192b07',
  "program_3_ex_5_desc":
      "• Fique de quatro, com o peso distribuído uniformemente. Os joelhos ficam embaixo dos quadris. A cabeça e o pescoço ficam em linha reta com a coluna. \n• Inspire e levante a cabeça até olhar para frente. \n• Expire e contraia a barriga para perto da coluna, trazendo os quadris para frente. Posicione o queixo no peito. \n• Repita quantas vezes desejar.",
  "program_4": "Exercícios para o pescoço",
  "program_4_ex_1_name": "Inclinação Lateral",
  "program_4_ex_1_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Tilt.mp3?alt=media&token=fe2671d0-c001-4ccd-8a09-8ff380a75355',
  "program_4_ex_1_desc":
      "- Mantenha a cabeça direita. \n- Coloque a sua mão direita na orelha esquerda e dobre suavemente a cabeça para o ombro direito, pare se sentir desconforto. \n- Mude de mãos. ",
  "program_4_ex_2_name": "Inclinação frontal e traseira",
  "program_4_ex_2_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FForward%20and%20Backward%20Tilt.mp3?alt=media&token=346ffde3-4cd3-460c-928e-9f9ab177512f',
  "program_4_ex_2_desc":
      "• Comece com a cabeça e as costas retas. \n• Abaixe o queixo em direção ao peito e volte à posição inicial. \n• Incline o queixo em direção ao teto e traga a base do crânio em direção às costas. \n• Repita esse exercício diversas vezes.",
  "program_4_ex_3_name": "Rotação Lateral",
  "program_4_ex_3_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FSide%20Rotation.mp3?alt=media&token=da9612fe-6559-47ce-83a1-a52a037ce63f',
  "program_4_ex_3_desc":
      "• Mantenha a cabeça e as costas eretas. \n• Gire lentamente a cabeça para a direita e para a esquerda, até sentir um alongamento na lateral do pescoço e do ombro.",
  "program_4_ex_4_name": "Rotação da cabeça",
  "program_4_ex_4_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FHead%20rotation.mp3?alt=media&token=c5817357-2218-400a-bde1-3d8509c1dbb3',
  "program_4_ex_4_desc":
      "- Sente-se ou fique de pé com a cabeça e as costas direitas. \n- Rodar a cabeça no sentido dos ponteiros do relógio e no sentido contrário 3 vezes.",
  "program_4_ex_5_name": "Rotação dos ombros",
  "program_4_ex_5_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FShoulders%20rotation.mp3?alt=media&token=ad9f4128-bbe2-42b1-be88-4f9a3a75310e',
  "program_4_ex_5_desc":
      "- Coloque as pernas à largura dos ombros, mantenha os braços relaxados. \n- Efectue uma rotação suave de ambos os ombros no sentido dos ponteiros do relógio e no sentido contrário aos ponteiros do relógio.",
  "program_4_ex_6_name": "Postura da vaca",
  "program_4_ex_6_audio":
      'https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_audio%2FCow%20Face%20Pose.mp3?alt=media&token=1654d6bc-dba2-4063-a674-9bd4519eb110',
  "program_4_ex_6_desc":
      "- Mantenha-se direito, mantenha os seus ombros relaxados. \n- Feche as mãos atrás das costas, para que um braço esteja para cima, outro esteja para baixo. Sinta o alongamento. \n- Mude de mãos e faça novamente. ",
  "exercise_1_title": "Alongamento",
  "exercise_1_text":
      "Comece com um alongamento. \n\n1. Fique de pé em linha reta, com os pés abertos além da largura dos ombros.\n\n2. Enquanto está de pé, feche as mãos para cima e com as palmas voltadas para o teto.\n\n3. Alongue-se lentamente para cima.\n\n4. Mantenha a cabeça e as costas eretas, sem dobrar.\n\n5. Mantenha por 10 a 15 segundos, e repita de três a quatro vezes.",
  "exercise_2_title": "Marcha",
  "exercise_2_text":
      "1. Os pés humanos possuem muitas terminações nervosas e elas são responsáveis por ajudar no trabalho dos órgãos. \n\n2. Fique de pé, com os pés afastados na distância dos ombros e mantenha a coluna ereta, com os quadris voltados para a frente. Levante o joelho para que a coxa fique paralela ao chão. Em seguida, abaixe essa perna e levante a outra, de forma alternada.\n\n3. Repita esse exercício por cinquenta segundos.",
  "exercise_3_title": "Elevações dos calcanhares e dedos dos pés",
  "exercise_3_text":
      "1. Fique de pé.\n\n2. Coloque os pés a 15 polegadas de distância um do outro.\n\n3. Inspire e levante os dedos dos pés, abaixe, levante os calcanhares, abaixe-os e expire. Repita de 20 a 25 vezes.",
  "exercise_4_title": "Rotações",
  "exercise_4_text":
      "1. Os exercícios rotativos são ótimos aquecimentos.\n\n2. Comece com a cabeça, em seguida vá para os pulsos, cotovelos, ombros, pés, tornozelos e joelhos.\n\n3. Repita em cada parte do corpo, com pelo menos 10 vezes de cada lado.",
  "exercise_5_title": "Alternando entre inclinação e agachamentos",
  "exercise_5_text":
      "Um exercício simples mas eficaz, que ajuda a trabalhar muitos músculos importantes.\n\n1. Fique de pé e ereto, com os pés abertos além da largura dos ombros, e fique com as mãos na cintura.\n\n2. Incline-se suavemente para baixo, mantendo as costas eretas e faça um agachamento.\n\n3. Preste atenção à sua postura para evitar lesões nos joelhos.\n\n4. Faça 10-20 repetições.",
  "exercise_6_title": "Curva lateral em pé",
  "exercise_6_text":
      "1. Fique em pé, com os pés um pouco mais afastados do que a distância do quadril.\n\n2. Levante a mão direita.\n\n3. Abaixe o braço direito junto ao corpo e expire, enquanto alonga o braço esquerdo sobre a sua cabeça, dobrando o corpo suavemente para a direita.\n\n4. Inspire e retorne os braços para a posição inicial, e expire enquanto repete para o lado esquerdo.\n\n5. Faça pelo menos 15 repetições para cada lado",
  "exercise_7_title": "BAbdominal bicicleta",
  "exercise_7_text":
      "1. Deite-se com as costas no chão.\n\n2. Seus pés devem estar no chão e suas mãos atrás da cabeça.\n\n3. Com as mãos segurando a cabeça suavemente, levante os joelhos em um ângulo de cerca de 90 graus e levante os pés do chão.\n\n4. Gire o tronco para que você possa tocar o cotovelo no joelho oposto à medida que faz o exercício. \n\n5. Faça 15 repetições para cada perna.",
  "exercise_8_title": "Gato e Cão",
  "exercise_8_text":
      "Este exercício melhora a flexão\n e a extensão da coluna vertebral. 1. Coloque as mãos e os joelhos no chão.\n\n2. Num movimento fluido, arqueie as costas, sugue o estômago e traga as ancas para a frente.\n\n3. Agora olhe para cima em vez de olhar para as pernas ou para o chão.\n\n4. Repita pelo menos 15 vezes para cada lado",
  "exercise_9_title": "Flexão",
  "exercise_9_text":
      "1. Você pode fazer flexões ao se apoiar com os dedos dos pés e com o joelho. A segunda é considerada mais fácil.\n\n2. Mantenha o corpo em linha reta e os cotovelos próximos ao corpo, dobre os braços e empurre para completar uma flexão.\n\n3. Se a primeira opção for difícil, apoie-se sobre o joelho e repita as instruções do primeiro exercício.\n\n4. Faça 15 flexões",
  "exercise_10_title": "Alongamento da mão",
  "exercise_10_text":
      "1. Estenda os braços com as palmas voltadas para cima em direção ao teto.\n\n2. Expire enquanto estende os braços em direção ao teto.\n\n3. Inspire enquanto volta e relaxe.\n\n4. Repita até 5 vezes, e alongue as mãos por 10 segundos em cada vez.",
  "fitness": "FITNESS",
  "fitness_title": "Exercícios que ajudam a restaurar a sua \nsaúde física",
  "good_morning": "Bom dia",
  "good_afternoon": "Boa tarde",
  "good_evening": "Boa noite",
  "good_night": "Boa noite",
  "meditation": "MEDITAÇÃO",
  "meditation_title":
      "Sente-se em uma posição\nconfortável e concentre-se na\nsua respiração.",
  "meditation_select": "Escolha uma Meditação",
  "meditation_menu_1": "Silêncio",
  "meditation_menu_2": "Apenas música",
  "meditation_menu_3": "Meditação guiada",
  "note": "NOTA",
  "fitness_program": "Programa pronto",
  "fitness_my_program": "Fazer meu programa",
  "visualization": "VISUALIZAÇÃO",
  "visualization_title":
      "Feche os olhos e imagine o seu objetivo. Toque-o, sinta-o, imagine o passo a passo do seu caminho",
  "visualization_hint": "Escreva a sua visualização de maneira breve",
  "diary": "DIÁRIO",
  "voice_record": "Um registro de voz",
  "written_record": "Um registro escrito",
  "affirmation": "FRASES AFIRMATIVAS",
  "affirmation_title":
      "Pronuncie claramente, \nem voz alta, \ncom total confiança e concentração",
  "your_name": "Seu nome",
  "google": "Iniciar sessão com o Google",
  "apple": "Iniciar sessão com a Apple",
  "restart": "Reiniciar",
  "menu": "Menu",
  "day": "Dia",
  "min": "min",
  "sec": "seg",
  "pull_program":
      "Para configurar o seu programa,\n adicione os exercícios acima",
  "add_exercises": "Adicionar\nexercícios",
  "success": "Sucesso!",
  "vip_restored": "Assinaturas restauradas",
  "pages": "Quantas páginas?",
  "continue": "Continuar",
  "change_tarif": "Alterar tarifa",
  "reminders": "Lembretes",
  "add_first_reminder": "Adicione o seu primeiro lembrete",
  "select_week_day": "Selecione os dias da semana",
  "set_reminders": "Configurar um Lembrete",
  "stop": "Parar",
  "push_success": "Sucesso!",
  "action_completed": "ação concluída!",
  "timer_started": "Temporizador\niniciado",
  "appreciate":
      "Nós nos importamos com o seu aconchego e conforto, e, portanto, liberamos os recursos do aplicativo. Assim, você não vai se distrair com anúncios.",
  "subscribe_futures":
      "Subscription will provide the opportunity to perform exercises such as: Fitness, Diário, Leitura e Visualização. A assinatura é renovada automaticamente todos os meses, mas você pode cancelá-la a qualquer momento.",
  "price": "Preço",
  "tarif_month_title": "@days dias gratuitos",
  "tarif_month_desc": "após isso, @price por mês",
  "tarif_annual_title": "@price por ano",
  "tarif_annual_desc": "@price por mês",
  "well_done": "Muito bem!",
  "well_done_desc":
      "Comece as suas manhãs da maneira certa, tenha gratidão por si mesmo e pelo seu dia.",
  "buy_month": "Adquirir assinatura",
  "buy_free": "EXPERIMENTE A ROTINA COMPLETA",
  "days_free": "@days dias gratuitos",
  "buy_days": "Experimente por @days dias grátis",
  "sure": "Você tem certeza?",
  "sure_delete": "Tem certeza de que deseja excluir o exercício?",
  "cancel": "Cancelar",
  "skip": "Pular",
  "minutes": "minutos",
  "choose_sequence": "Escolha a\nsequência",
  "choose": "Escolher",
  "done": "Pronto",
  "choose_title":
      "Arraste e solte para alterar a sequência de exercícios e definir um período para eles.\n0 min - pular exercício.",
  "exercises_note": "Exercícios",
  "visualizations_note": "Visualização",
  "seconds": "segundos",
  "affirmation_small": "Frases afirmativas",
  "affirmation_smal": "Frases\nafirmativas",
  "meditation_small": "Meditação",
  "fitness_small": "Fitness",
  "diary_small": "Diário",
  "menu_diary_small": "Diário",
  "Save the Affirmation": "Salvar a Afirmação",
  "or": "ou",
  "Affirmation Settings": "Affirmation Settings",
  "menu_diary_desc": "Anote pensamentos importantes em seu diário",
  "reading_small": "Leitura",
  "visualization_small": "Visualização",
  "fitness_desc": "Aprimore a sua aptidão",
  "visualization_desc": "Visualize o seu objetivo",
  "reading_desc": "Inspire-se com livros pela manhã",
  "duration": "Duração de",
  "complex": "complexo: ",
  "magic_morning": "“Manhã maravilhosa”",
  "write_affirmation": "Escreva a sua \nfrase afirmativa",
  "affirmation_hint": "Escreva a sua Afirmação...",
  "book_name": "Escreva o nome \ndo livro",
  "input_cat_name": "Nome da categoria",
  "input_desc": "Insira uma descrição",
  "player_voice": "Voz",
  "female": "Feminina",
  "male": "Masculina",
  "complexs": "complex",
  "language": "Idioma",
  "Add a reminder": "Acrescentar um lembrete",
  "Are you sure you want to leave the complex":
      "Tem a certeza que quer deixar o complexo",
  "x_minutes": "@x minutos",
  "Monday": "Segunda-feira",
  "Tuesday": "Terça-feira",
  "Wednesday": "Quarta-feira",
  "Thursday": "Quinta-feira",
  "Friday": "Sexta-feira",
  "Saturday": "Sábado",
  "Sunday": "Domingo",
  "leave": "Sair",
  "January": "Janeiro",
  "February": "Fevereiro",
  "March": "Março",
  "April": "Abril",
  "Mayi": "Maio",
  "June": "Junho",
  "July": "Julho",
  "August": "Agosto",
  "September": "Setembro",
  "October": "Outubro",
  "November": "Novembro",
  "December": "Dezembro",
  "Are you sure you want to delete a note?":
      "Tem a certeza de que quer apagar\n uma nota?",
  "How much time are you going to read?": "Quanto tempo vai ler?",
  "Delete a note": "Apagar uma nota",
  "add_exercise": "Adicionar exercício",
  "Organize your morning routine with ease using the complex program":
      "Organize a sua rotina matinal com\nfacilidade,utilizando o programa\ncomplexo.",
  "name": "Nome",
  "komplex": "Complexo - ",
  "Personalize a sequência e duração dos seus rituais no":
      "Customize the sequence and duration of your rituals in",
  "Settings section": " Secção Definições",
  "is a consistent set of your morning daily rituals. ":
      "é um conjunto consistente dos seus rituais diários matinais. ",
  "please_input_name": "Insira o seu nome",
  "delete_exercise": "Excluir exercício",
  "delete_hint": "Toque e segure\n para excluir",
  "your_exercise": "Seu exercício",
  "enter_your_exercise": "Digite seu exercício",
  "add_permission": "Conceder permissão para gravar áudio",
  "yes": "Sim",
  "For instance": "Por exemplo",
  "1) Meditation - 5 minutes2) Fitness & Yoga - 15 minutes 3) Reading - 20 minutes":
      "1) Meditação - 5 minutos\n2) Fitness & Yoga - 15 minutos \n3) Leitura - 20 minutos",
  "no": "Não",
  "other": "Outro",
  "save_diary": "Salvar nota",
  "Start reading": "Comece a ler",
  "Start affirmation": "Iniciar a afirmação",
  "mornings": "Manhã ",
  "enter_your_name": "Digite seu nome",
  "remove_progress": "Remover o progresso",
  "sure_delete_progress":
      "Tem certeza de que deseja excluir todo o progresso do aplicativo?",
  "and": " e ",
  "agreement_start": "Ao clicar em “Próximo”, você confirma que aceita os",
  "agreement_title": "Termos de Uso",
  "privacy_title": "Política de Privacidade",
  "paragraph1": "Registre pensamentos importantes em notas",
  "paragraph2": "Aprimore a sua aptidão",
  "paragraph3": "Inspire a sua manhã com livros",
  "paragraph4": "Visualize o seu objetivo",
  "try_vip_desc":
      "Experimente por dias gratuitamente e, em seguida, pague apenas @price por mês.\n Você pode cancelar sua assinatura a qualquer momento",
  "vip_price_card": "1 mês",
  "vip_def_month_price": "0.99US\$",
  "for_confidence": "Melhore a sua confiança",
  "for_health": "Melhore a sua saúde",
  "for_love": "Melhore a sua vida romântica",
  "for_success": "Melhore o seu sucesso",
  "for_career": "Melhore a sua carreira",
  "for_wealth": "Melhore a sua prosperidade",
  "confidence_text_1": "Desafios são oportunidades para crescer e melhorar",
  "confidence_text_2": "Eu acredito nas minhas habilidades",
  "confidence_text_3": "Não existem bloqueios que eu não consiga superar",
  "confidence_text_4":
      "Eu sou digno de viver minha vida e de alcançar os meus objetivos",
  "confidence_text_5":
      "Eu me permito escolher meu próprio caminho e realizar os meus sonhos",
  "confidence_text_6": "Eu amo quem eu sou, por dentro e por fora",
  "health_text_1":
      "Meu corpo sabe como se curar. Eu permito que a inteligência do meu corpo mude a minha saúde de maneira positiva",
  "health_text_2":
      "Eu acredito na minha intuição. Eu sempre escuto minha voz interior",
  "health_text_3":
      "Eu consigo dormir facilmente. Meu corpo, mente e alma são dignos de seu descanso",
  "health_text_4":
      "Estou em harmonia com o meu eu interior, que conhece os segredos da cura",
  "health_text_5": "Eu me torno mais saudável e forte a cada dia",
  "health_text_6": "Eu tenho muita energia e poder vital",
  "health_text_7":
      "Eu estou no controle da atmosfera mental que eu crio. Eu posso mudar meus pensamentos, e os pensamentos positivos que eu escolho estão me ajudando no meu processo de cura",
  "health_text_8": "Eu sou saudável, feliz e radiante",
  "health_text_9": "Eu mereço ter uma boa saúde",
  "health_text_10": "Eu irradio boa saúde",
  "love_text_1":
      "Eu entrego todo o meu coração, e posso receber o coração de outra pessoa",
  "love_text_2": "Eu sinto amor na minha direção",
  "love_text_3": "Eu mereço amor e carinho",
  "love_text_4": "Eu tenho muito carisma",
  "love_text_5":
      "Eu dou permissão para que a minha deusa interior faça o seu trabalho",
  "love_text_6": "Eu abraço a ideia de ser uma mulher",
  "love_text_7": "Tenho confiança na minha sexualidade",
  "love_text_8":
      "Gosto da ideia de um relacionamento saudável e amoroso, e que seja o ideal para mim",
  "love_text_9": "Mereço ter realização, sucesso e abundância",
  "love_text_10": "Mereço ter um relacionamento saudável e amoroso",
  "love_text_11":
      "Estou em um relacionamento maravilhoso, com uma pessoa que me trata muito bem!",
  "success_text_1":
      "Tenho a mente aberta e mal posso esperar para explorar novos caminhos para o sucesso",
  "success_text_2":
      "Tenho o poder de criar todo o sucesso e prosperidade que desejo",
  "success_text_3": "Tenho organização e administro bem o meu tempo",
  "success_text_4":
      "Sou capaz de alçar voos altos e sempre correspondo às minhas expectativas",
  "success_text_5": "Confio na minha intuição e sempre tomo decisões sábias",
  "success_text_6":
      "Eu atraio as circunstâncias certas, no momento certo e de maneira bem sucedida",
  "success_text_7":
      "Eu recebo novas ideias diariamente, que me motivam e me inspiram",
  "success_text_8": "Tenho poder ilimitado para conseguir tudo o que quero",
  "success_text_9": "Tomo decisões inteligentes de maneira alegre",
  "success_text_10": "O Universo quer me ajudar e me dar tudo o que eu preciso",
  "success_text_11":
      "Eu tenho a coragem de usar todos os presentes que a vida me dá",
  "career_text_1":
      "Tenho motivação, tenho foco nos meus objetivos e auto-consciência",
  "career_text_2": "Eu sempre alcanço meus objetivos de carreira",
  "career_text_3": "Ter sucesso no trabalho é fácil",
  "career_text_4": "As pessoas me respeitam e me tratam bem",
  "career_text_5":
      "Neste exato momento, meu currículo está sendo analisado pelas pessoas certas",
  "career_text_6":
      "Eu mereço um trabalho que me realize, e sou capaz de encontrá-lo!",
  "career_text_7":
      "Enquanto alinho minha carreira com meus verdadeiros talentos, o dinheiro e a felicidade estão fluindo para mim!",
  "career_text_8":
      "Eu me esforço! Eu trabalho de maneira inteligente! Eu mereço os elogios que recebo!",
  "career_text_9": "Eu uso meus talentos da melhor maneira todos os dias!",
  "career_text_10": "Eu adapto a minha carreira aos meus objetivos!",
  "career_text_11": "Tenho segurança financeira, e faço o que quero",
  "wealth_text_1": "Eu atraio a boa sorte de maneira natural",
  "wealth_text_2": "O dinheiro é meu amigo",
  "wealth_text_3": "Eu consigo ganhar e gastar dinheiro com facilidade!",
  "wealth_text_4":
      "Eu sou um ímã para atrair dinheiro! O dinheiro flui livremente para mim",
  "wealth_text_5":
      "Eu tenho uma relação positiva com o dinheiro e sei como gastá-lo de maneira sábia",
  "wealth_text_6":
      "Eu reconheço as oportunidades de ganhar dinheiro! Eu sei converter oportunidades em sucessos!",
  "wealth_text_7": "Possuo conexão com o fornecimento universal de dinheiro",
  "wealth_text_8": "O Universo me enche de presentes",
  "wealth_text_9": "Toda boa ação volta para mim em dobro",
  "wealth_text_10": "Eu atraio muitos recursos e ideias",
  "start_program": "Iniciar programa",
  "program_settings": "Configurações do programa",
  "restore_default": "Restaurar\npadrões",
  "create_yours": "Criar\nsua",
  "restore": "Restaurar assinatura",
  "delete": "Excluir",
  "edit": "Editar",
  "cancellation": "Cancelar",
  "exercises": "Exercícios",
  "add_yours": "Crie o seu",
  "save": "Salvar",
  "delete_program_alert": "Tem certeza de que deseja excluir um programa?",
  "initial_exercises_empty":
      "Os exercícios padrão já foram adicionados. Tente criar o seu próprio exercício",
  "restore_default_dialog_title":
      " Tem certeza de que deseja restaurar os exercícios ao padrão?Os programas/exercícios do usuário serão excluídos",
  "name_not_be_empty": "O campo “Nome” não pode estar vazio",
  "type_exercise_name": "Digite um nome para o exercício",
  "type_program_name": "Digite um nome para o programa",
  "type_exercise_description": "Digite uma descrição para o exercício",
  "hold_to_move_exercise": "Segure para mover um exercício",
  "type_name": "Digite um nome",
  "tutorial_text": "Levantar de manhã é fácil para você?",
  "rate_app_title": "Avaliar App",
  "rate_app_description": "Sua avaliação nos ajudará a melhorar",
  "action_rate": " Avaliar",
  "action_remind": "Lembre-me depois",
  "rate_subject": "Avaliar o aplicativo",
  "my_progress": "MEU PROGRESSO",
  "Try PREMIUM": "Experimente PREMIUM",
  "3 days free": "3 dias livres",
  "Finish reading": "Leitura final",
  "exercise_complete": "Exercício concluído",
  "affirmation_timer": "Frases afirmativas",
  "audio_loading": "O áudio está carregando...",
  "success_target": "Sucesso",
  "family_target": "Família",
  "nature_target": "Natureza",
  "rest_target": "Repouso",
  "sport_target": "Esporte",
  "target_selection": "Selecionar o destino",
  "remove_created_target": "Remover alvo criado?",
  "impression_selection": "Selecionar impressão",
  "remove_image": "Remover imagem?",
  "target_title": "título",
  "target_short_desc":
      "no campo, descreva brevemente (em uma frase) o que você visualizará",
  "music_menu_music": "Música",
  "music_menu_sounds": "Sons",
  "music_menu_meditations": "Meditações",
  "music_menu_favorite": "Favorito",
  "purchase_page_title": "Suas manhãs nunca mais serão as mesmas",
  "purchase_page_desc": "@days dias gratuitos",
  "go_start_record": "Toque para iniciar a gravação",
  "go_stop_record": "Gravação em andamento, toque para parar",
  "empty_favorite_list": "Você não tem músicas salvas",
  "purchase_bonuses_image": "assets/images/purchase/bonuses_en.png",
  "faq_menu_title": "Perguntas frequentes",
  "faq_cat_support": "Suporte",
  "faq_cat_why": "Para que isso serve?\n",
  "faq_cat_tarifs": "Perguntas sobre a assinatura\n ",
  "faq_tarifs_title_1": "Quais são os benefícios de uma assinatura?",
  "faq_tarifs_desc_1":
      "<p>- remove anúncios <br>- acesso às seções fitness, diário, leitura, visualizações <br>- acesso novos recursos de rotinas.</p>",
  "faq_tarifs_title_2": "Por que o aplicativo não é gratuito?",
  "faq_tarifs_desc_2":
      "<p>- geralmente, bens gratuitos não são levados a sério. Se você não investir em uma ferramenta de autodesenvolvimento, você não vai se preocupar com o app.<br> Todo o dinheiro que recebemos dos assinantes é reinvestido em melhorias para o aplicativo</p>",
  "faq_tarifs_title_3": "Como mudar o valor da assinatura?",
  "faq_tarifs_desc_3":
      "<p>1. Vá para a aba <a href='screen tarifs'>«planos de assinatura»</a> <br>2. Selecione o plano desejado <br>3. Clique em alterar <br>4. No próximo mês, a tarifa será alterada</p>",
  "faq_tarifs_title_4": "Como restaurar uma assinatura?",
  "faq_tarifs_desc_4":
      "<p>A recuperação funciona apenas se você tiver uma assinatura ativa. Você pode clicar no botão \restaurar assinatura\" Ou fazê-lo manualmente <br>1. Vá para a aba <a href='screen tarifs'>«planos de assinatura»</a> <br>2. Clique na parte inferior para restaurar</p>",
  "faq_tarifs_title_5": "Como cancelar uma assinatura?",
  "faq_tarifs_desc_5":
      "<p>Você pode fazer isso manualmente ou ao clicar no botão <a href='screen:unsubscribe'>«Cancelar assinatura»</a></p>",
  "faq_tarifs_title_6": "Atendimento ao cliente",
  "faq_about_title_1": "Para que servem esses exercícios?",
  "faq_about_desc_1":
      "<p>Meditação - ajuda a despertar a mente gradualmente e a manter a calma <br>Frases afirmativas - enche a mente com energias positivas <br>Visualizações - permite que você visualize o seu objetivo com precisão <br>Fitness - energiza seu corpo <br>Leitura - Inicie a sua manhã aumentando os seus conhecimentos! (especialmente se não houver tempo suficiente à noite) <br>Diário - guarde recordações do que você fez e do que aprendeu ao anotar os pensamentos mais importantes <br>É melhor dedicar uma hora por dia para criar uma rotina, mas se você conseguir realizar pelo menos algumas práticas já vai conseguir notar resultados positivos.</p>",
  "faq_about_title_2": "Como usar o app?",
  "faq_about_desc_2":
      " <p>Vá em \"configurações\" ali, você pode definir: - o <br>tempo de cada prática <br>- A sequência da rotina <br>- Frases afirmativas por padrão <br>- O livro que você está lendo atualmente. <br>As configurações podem ser alteradas a qualquer momento. <br>Depois de configurar, você pode clicar no botão\"iniciar\", e tudo acontecerá de acordo com as configurações que selecionou</p>",
  "faq_about_title_3": "Por que eu deveria usar esse app?",
  "faq_about_desc_3":
      "<p>A prática ajuda você a focar mais no seu dia, fornecendo animação extra e ajudando você a se livrar do estresse <br>Inúmeras pessoas bem sucedidas optam por acordar mais cedo a fim de alcançar resultados melhores. Mas também é útil se você quiser apenas recarregar suas energias ou se quiser melhorar sua atitude mental.</p>",
  "faq_about_title_4": "Quando os resultados começam a aparecer?",
  "faq_about_desc_4":
      "<p>Será possível desenvolver um hábito após 10 dias <br>Após um mês de uso, você perceberá que o seu despertar pela manhã ficou mais fácil e que o estresse se tornou visivelmente menor.</p>",
  "faq_about_title_5": "Como configurar o recurso fitness?",
  "faq_about_desc_5":
      "<p>1. Clique em <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F02-min%20(1).png?alt=media&token=5f53f785-9dd5-4a46-957e-0f8a7dca7f62' width='25' /> em ambientes <br>2. Seleccione o programa que deseja editar <br>3. Clique em editar <br>Há algum problema? <a href='screen:support'>apoio</a></p>",
  "faq_about_title_6": "Como configurar as visualizações?",
  "faq_about_desc_6":
      "<p>1. Para adicionar um alvo, clique no botão <img alt='settings' src='https://firebasestorage.googleapis.com/v0/b/my-morning-b0697.appspot.com/o/en_dart_images%2F01-min.png?alt=media&token=17783548-ef94-40ed-87ed-db6a3979e0ac' width='25' /> na selecção do alvo <br>2. Depois seleccione a imagem de entre as imagens guardadas no seu telefone <br>3. Esperar enquanto as fotografias estão carregadas <br>4. Pode usar objectivos e imagens já prontos, ou adicionar as suas próprias imagens a objectivos usando as mesmas instruções. <br>Há algum problema? <a href='screen:support'>apoio</a></p>",
  "welcome_to_sleep": "Bem-vindo ao Sleep",
  "meditation_subtitle":
      "Ouça uma de nossas meditações para aliviar o estresse",
  "music_for_sleep_subtitle": "Durma com sua música favorita",
  "music_for_sleep_title": "Músicas para dormir",
  "reading_at_night_title": "Leitura à noite",
  "reading_at_night_subtitle": "Se você gostar de ler antes de dormir",
  "music_instrument_title": "Instrumentos musicais",
  "instrument_1": "Harpa",
  "instrument_2": "Glucofone",
  "instrument_3": "Gaita",
  "instrument_4": "Colher de madeira",
  "instrument_5": "Canção de Ninar",
  "Do you have trouble": "Tem problemas",
  "What do you want to ": "O que deseja ",
  "concentrating?": " concentrando?",
  "to get out of My Morning?": "para sair\ndo My Morning?",
  "instrument_6": "Piano",
  "instrument_7": "Violino",
  "instrument_8": "Flauta",
  "music_instrument_places": "Locais",
  "onb3p1": "Continuar",
  "place_1": "Na cafeteria",
  "place_2": "Vila",
  "place_3": "Trem",
  "place_4": "Fluxo de carros",
  "place_5": "Avião",
  "place_6": "Construção",
  "place_7": "Multidão",
  "music_instrument_other": "Outro",
  "other_1": "Ventilador",
  "other_2": "Limpadores de para-brisa",
  "other_3": "Teclado",
  "other_4": "Sinos",
  "other_5": "Coração",
  "other_6": "Relógio",
  "music_instrument_sound_of_nature": "Sons da natureza",
  "nature_1": "Vento batendo na grama",
  "nature_2": "Cachoeira",
  "nature_3": "Nevasca e neve",
  "nature_4": "Trovão",
  "nature_5": "Chuva batendo no guarda-chuva",
  "nature_6": "Chuva batendo na tenda",
  "nature_7": "Chuva em uma poça",
  "nature_8": "Trovoada",
  "nature_9": "Chuva",
  "nature_10": "Gotejando",
  "nature_11": "Chuva torrencial",
  "nature_12": "Fogo",
  "nature_13": "Lago",
  "nature_14": "Oceano",
  "nature_15": "Embaixo d'água",
  "nature_16": "Córrego",
  "nature_17": "Ventos fortes",
  "nature_18": "Pisando na neve",
  "nature_19": "Brisa na grama",
  "music_instrument_living_creatures": "Seres vivos",
  "creatures_1": "Baleia",
  "creatures_2": "Gato tomando leite",
  "creatures_3": "Cavalo galopando",
  "creatures_4": "O cavalo correndo",
  "creatures_5": "Sapo",
  "creatures_6": "Sapos",
  "creatures_7": "Gato ronronando",
  "creatures_8": "Pássaros",
  "creatures_9": "Pássaros 2",
  "creatures_10": "Grilos",
  "creatures_11": "Coruja",
  "creatures_12": "Gaivota",
  "save_selected": "Salvar seleção",
  "my_night": "Minha noite",
  "onb_1_text_1":
      "Olá!@dOferecerei mentoria para você e juntos criaremos uma manhã perfeita para você.",
  "onb_1_btn": "Como você pode me ajudar?",
  "onb_2_text_1":
      "Meu trabalho é@dcontrolar o caos cotidiano e criar um sistema que vai mudar fundamentalmente a sua vida.",
  "onb_2_btn": "Como é que a gente vai fazer isso?",
  "onb_3_text_1":
      "Você será@dresponsável por praticar uma certa rotina todas as manhãs. Isso lhe dará vivacidade, energia e motivação para o dia inteiro!",
  "onb_3_btn": "Como isso vai mudar a minha vida?",
  "onb_4_btn":
      "Legal! Você poderia me falar mais sobre\n                              os hábitos?",
  "onb_5_text_1":
      "O segredo está nos pequenos passos!@dDiariamente, você vai construir uma nova vida passo a passo, peça por peça. Eu garanto que você vai perceber uma diferença incrível em dois meses!",
  "onb_6_text_1": "Hábito nº 1",
  "onb_6_text_2": "Exercícios matinais",
  "onb_6_text_3":
      "Todo mundo sabe que tem que fazer, mas mesmo assim ninguém faz!@dSe conseguir fazer corretamente, isso vai te dar mais energia do que um café e é a maneira mais eficaz de revigorar e de acordar para valer!",
  "onb_6_text_4":
      "Prepare-se para praticar um conjunto de exercícios especiais, que em 5 minutos lhe trarão uma onda de energia e disposição para todo o dia!",
  "onb_6_btn": "Hábito nº 2",
  "onb_7_text_1": "Hábito nº 2",
  "onb_7_text_2": "Leitura",
  "onb_7_text_3":
      "As pessoas nunca têm tempo para isso!@dE o período da manhã é perfeito para ler livros, já que provavelmente todos que moram na casa ainda estão dormindo.",
  "onb_7_text_4":
      "Vou ajudar você a ler diariamente pelo menos um pouquinho. Lembre-se: o segredo está nos pequenos passos!",
  "onb_7_btn": "Hábito nº 3",
  "onb_8_text_1": "Hábito nº 3",
  "onb_8_text_2": "Planejamento",
  "onb_8_text_3":
      "Você precisa saber o que fazer se quiser ter um dia produtivo@dE é por isso que vamos te ajudar a escrever o seu plano diário todas as manhãs.",
  "onb_8_text_4":
      "Você anotará ou gravará seus planos e metas, assim como pensamentos e ideias, diretamente no aplicativo.",
  "onb_8_btn": "Hábito nº 4",
  "onb_9_text_1": "Hábito nº 4",
  "onb_9_text_2": "Meditação",
  "onb_9_text_3":
      "Limpe sua mente de pensamentos desnecessários.@dA meditação é uma prática extremamente viável. Ela afeta você imediatamente e esse efeito só aumenta com o tempo.",
  "onb_9_text_4":
      "As meditações estão incorporadas no aplicativo. Deixamos tudo prontinho para você: basta iniciar o app e praticar!",
  "onb_9_btn": "Hábito nº 5",
  "onb_10_text_1": "Hábito nº 5",
  "onb_10_text_2": "Frases afirmativas",
  "onb_10_text_3":
      "Você tem sonhado com alguma@dcoisa por muito tempo? A prática das frases afirmativas permite reprogramar o seu subconsciente e configurá-lo para cumprir seus objetivos e desejos.",
  "onb_10_text_4":
      "O sistema de frases afirmativas permitirá que você pratique de forma natural e eficaz.",
  "onb_10_btn": "Tem mais alguma coisa?",
  "onb_11_text_1": "Estatísticas completas",
  "onb_11_text_2":
      "Você também pode encontrar estatísticas detalhadas de todos os seus hábitos para monitorar o seu progresso",
  "onb_11_text_3": "E aí, você está pronto para mudar a sua vida?",
  "onb_11_btn": "Estou! Então vamos lá!",
  "paywall_title": "Experimente o app MY MORNING\n DE GRAÇA",
  "popular": "Popular",
  "profitable": "Rentável",
  "cancel_subscribe_any_time": "Cancele a qualquer momento",
  "text": "Texto",
  "your_own_ritual": "Forme seus próprios hábitos",
  "support_text_title": "Responda à pesquisa",
  "support_text_body": "E ajude no desenvolvimento do aplicativo.",
  "voice_note": "Memorando de voz",
  "if_yes": "se assim for",
  "if_other": "se outro",
  "question": "Pergunta",
  "Secured with Apple Store": "Assegurado com a Apple Store",
  "Cancel anytime": "Cancelar a qualquer momento",
  "Try 3 days for free!": "Experimente 3 dias grátis!",
  "Try premium": "Experimente o Premium",
  "Free!": "Free!",
  "Limited Offer": "Oferta limitada",
  "3 days": "3 dias",
  "Free": "Free",
  "After": "Depois de",
  "Create your perfect morning": "Crie a sua manhã perfeita",
  "Payment every 12 months": "Pagamento de 12 em 12 meses",
};
